import {bindThrottle} from './controls.js?v=010';
import {HoodCamera,CAMERA_CONFIG} from './cameras.js?v=010';
import {RoadWorld,ROAD_CONFIG} from './road-world.js?v=010';
import {VisualCar} from './visual-car.js?v=010';
import {OffroadVehicle,CAR_CONFIG,rotate} from './physics.js?v=010';
import {EngineAudio} from './engine-audio.js?v=010';
const canvas=document.querySelector('canvas'),gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl){document.querySelector('#error').hidden=false;document.querySelector('#error').textContent='WebGL недоступен. Открой сайт в Safari или Chrome.';throw Error('WebGL unavailable');}
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
const fragmentPrecision=gl.getShaderPrecisionFormat?.(gl.FRAGMENT_SHADER,gl.HIGH_FLOAT)?.precision>0?'highp':'mediump';
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,`attribute vec3 p;attribute vec3 n;attribute vec3 t;varying vec3 ground;varying vec3 roadUV;uniform mat4 mvp;uniform mat4 model;uniform vec3 eye;varying float light;varying float fog;void main(){ground=p;roadUV=t;light=.6+.4*max(dot(normalize(mat3(model)*n),normalize(vec3(-.5,1.,.3))),0.);gl_Position=mvp*vec4(p,1.);fog=distance((model*vec4(p,1.)).xyz,eye);}`));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision ${fragmentPrecision} float;uniform vec3 color;uniform float style;varying vec3 ground;varying vec3 roadUV;varying float light;varying float fog;
float hash(vec2 p){return fract(sin(dot(mod(p,64.),vec2(12.9898,78.233)))*437.58);}
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);}
void main(){vec3 c=color;if(style>0.){vec2 uv=roadUV.xy;float broad=noise(uv*.15),grain=noise(uv*2.);c*=.91+.15*broad+.035*grain;if(style<1.5){c=mix(c,vec3(.48,.43,.31),smoothstep(.62,.88,broad)*.26);c+=vec3(.025,.018,.009)*(grain-.5);float rut=exp(-pow((abs(roadUV.y)-.84)/.21,2.));c*=1.-.075*rut;float edge=smoothstep(.80,1.,abs(roadUV.z)+.05*(broad-.5));c=mix(c,vec3(.43,.50,.34),edge*.75);}if(style>2.5&&style<3.5)c*=.92+.08*sin(roadUV.x*13.);if(style>3.5)c=mix(c,vec3(.55,.66,.63),pow(max(0.,noise(uv*.8)-.3),3.)*.5);}gl_FragColor=vec4(mix(c*light,vec3(.73,.79,.74),smoothstep(170.,440.,fog)),1.);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);const loc={};for(const k of ['mvp','model','color','eye','style'])loc[k]=gl.getUniformLocation(program,k);for(const k of ['p','n','t'])loc[k]=gl.getAttribLocation(program,k);
function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function matrix(x,y,z,sx,sy,sz,a=0){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c*sx,0,-s*sx,0,0,sy,0,0,s*sz,0,c*sz,0,x,y,z,1]);}
function norm(v){const d=Math.hypot(...v)||1;return v.map(x=>x/d);}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}function dot(a,b){return a.reduce((s,v,i)=>s+v*b[i],0);}function view(e,t,up=[0,1,0]){const z=norm(e.map((v,i)=>v-t[i])),x=norm(cross(up,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1]);}
function mesh(v,n,t=new Array(v.length).fill(0)){function buf(data){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);return b;}return{p:buf(v),n:buf(n),t:buf(t),count:v.length/3};}
const v=[],n=[];for(let axis=0;axis<3;axis++)for(const sign of [-1,1]){const corners=[];for(const [u,w] of [[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]]){const p=[0,0,0];p[axis]=sign*.5;p[(axis+1)%3]=u;p[(axis+2)%3]=w;corners.push(p);}const normal=[0,0,0];normal[axis]=sign;for(const i of [0,1,2,0,2,3]){v.push(...corners[i]);n.push(...normal);}}const cube=mesh(v,n);
const rv=[],rn=[];for(let i=0;i<12;i++){const a=i*Math.PI/6,b=(i+1)*Math.PI/6;const points=[[Math.cos(a)*.5,-.5,Math.sin(a)*.5],[Math.cos(b)*.5,-.5,Math.sin(b)*.5],[Math.cos(b)*.5,.5,Math.sin(b)*.5],[Math.cos(a)*.5,.5,Math.sin(a)*.5]];for(const j of [0,1,2,0,2,3]){rv.push(...points[j]);rn.push(Math.cos((a+b)/2),0,Math.sin((a+b)/2));}for(const y of [-.5,.5])for(const p of [[0,y,0],[Math.cos(a)*.5,y,Math.sin(a)*.5],[Math.cos(b)*.5,y,Math.sin(b)*.5]]){rv.push(...p);rn.push(0,Math.sign(y),0);}}const cylinder=mesh(rv,rn);
let pv;function draw(shape,m,col,style=0){gl.uniform1f(loc.style,style);for(const k of ['p','n','t']){gl.bindBuffer(gl.ARRAY_BUFFER,shape[k]);gl.vertexAttribPointer(loc[k],3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(loc[k]);}gl.uniformMatrix4fv(loc.model,false,m);gl.uniformMatrix4fv(loc.mvp,false,mul(pv,m));gl.uniform3fv(loc.color,col);gl.drawArrays(gl.TRIANGLES,0,shape.count);}
// A bounded rolling corridor replaces the finite polygon.
const parameters=new URLSearchParams(globalThis.location?.search||''),debug=parameters.has('debug'),world=new RoadWorld(parameters.get('seed')||ROAD_CONFIG.seed);
const height=(x,z)=>world.height(x,z),groundNormal=(x,z)=>world.normal(x,z),sampleSurface=(x,z)=>world.surface(x,z),grip=(x,z)=>sampleSurface(x,z).longitudinalGrip;
const physics=new OffroadVehicle({height,normal:groundNormal,grip,surface:sampleSurface},{...CAR_CONFIG,mapLimit:Infinity}),sound=new EngineAudio(document.querySelector('#sound'));const spawn=world.point(world.sections[0],18/world.sections[0].length);physics.reset(spawn.x,spawn.z,spawn.yaw);const visual=new VisualCar(physics);
const chunkSlots=new Map(),freeSlots=[];
function uploadGeometry(vertices,normals,old,uv=new Array(vertices.length).fill(0)){if(!old)return mesh(vertices,normals,uv);for(const [key,data] of [['p',vertices],['n',normals],['t',uv]]){gl.bindBuffer(gl.ARRAY_BUFFER,old[key]);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);}old.count=vertices.length/3;return old;}
export const VIEW_CONFIG={nearTrees:130,midTrees:260,drawDistance:550,fogStart:170,fogEnd:440};
function chunkLOD(section,pos){const dist=Math.max(0,section.startDistance-pos,pos-section.startDistance-section.length);return dist<VIEW_CONFIG.nearTrees?0:dist<VIEW_CONFIG.midTrees?1:2;}
function buildChunk(section,slot={},lod=0,decorOnly=false){const batches={};function triangle(key,a,b,c){const batch=batches[key]??={v:[],n:[],uv:[]},raw=norm(cross(b.map((x,i)=>x-a[i]),c.map((x,i)=>x-a[i]))),normal=raw[1]<0?raw.map(v=>-v):raw;for(const point of [a,b,c]){batch.v.push(...point);batch.n.push(...normal);batch.uv.push(...(point.uv||[0,0,0]));}}
 function at(node,lateral,water=false){const edge=Math.max(0,Math.abs(lateral)-node.width/2),y=node.y+.025*edge+.12*Math.sin(lateral*.2)**2*Math.min(1,edge/5)+world.localHeight(section,node.u,lateral)+(water?world.surfaceAt({section,u:node.u,lateral,width:node.width}).waterDepth:0);const point=[node.x+Math.cos(node.yaw)*lateral-section.entryTransform.x,y+(water?.02:0),node.z-Math.sin(node.yaw)*lateral-section.entryTransform.z];point.uv=[node.s%4096,lateral,lateral/(node.width/2)];return point;}
 if(!decorOnly)for(let i=0;i<section.nodes.length-1;i++){const a=section.nodes[i],b=section.nodes[i+1],fractions=[-1,-.8,-.5,-.3,-.2,0,.2,.3,.5,.8,1],half=(a.width+b.width)/4;
 for(const o of section.localFeatures)if(Math.abs((a.u+b.u)/2-o.u)*section.length<o.longRadius*3+1.5)for(const f of [-2,-1,-.5,0,.5,1,2])fractions.push(Math.max(-.99,Math.min(.99,(o.lateral+f*o.radius)/half)));
 if(section.special)for(const f of [-4,-section.special.deck,-section.special.deck+.05,section.special.deck-.05,section.special.deck,4])fractions.push(Math.max(-.99,Math.min(.99,f/half)));
 const fs=[...new Set(fractions)].sort((x,y)=>x-y),offsets=node=>[-650,-96,-48,-20,-12,-7,...fs.map(f=>f*node.width/2),7,12,20,48,96,650],aa=offsets(a),bb=offsets(b);
 for(let j=0;j<aa.length-1;j++){const lateral=(aa[j]+aa[j+1])/2,inside=Math.abs(lateral)<=a.width/2+.001,key=inside?world.visualMaterial(section,(a.u+b.u)/2,lateral):'GRASS',p=at(a,aa[j]),q=at(a,aa[j+1]),r=at(b,bb[j]),t=at(b,bb[j+1]);triangle(key,p,q,r);triangle(key,q,t,r);if(inside&&world.surfaceAt({section,u:(a.u+b.u)/2,lateral,width:a.width}).waterDepth>.016){triangle('WATER_TOP',at(a,aa[j],true),at(a,aa[j+1],true),at(b,bb[j],true));triangle('WATER_TOP',at(a,aa[j+1],true),at(b,bb[j+1],true),at(b,bb[j],true));}}

 }
 function boxPiece(key,x,y,z,sx,sy,sz,angle=0){const m=matrix(x-section.entryTransform.x,y,z-section.entryTransform.z,sx,sy,sz,angle),batch=batches[key]??={v:[],n:[]};for(let i=0;i<v.length;i+=3){batch.v.push(m[0]*v[i]+m[4]*v[i+1]+m[8]*v[i+2]+m[12],m[1]*v[i]+m[5]*v[i+1]+m[9]*v[i+2]+m[13],m[2]*v[i]+m[6]*v[i+1]+m[10]*v[i+2]+m[14]);batch.n.push(Math.cos(angle)*n[i]+Math.sin(angle)*n[i+2],n[i+1],-Math.sin(angle)*n[i]+Math.cos(angle)*n[i+2]);}}
 if(section.special&&!decorOnly){const sp=section.special;for(const u of [.5-(sp.gap+2)/section.length,.5+(sp.gap+2)/section.length]){const n=world.point(section,u);for(const side of [-1,1])boxPiece('WOOD',n.x+Math.cos(n.yaw)*side*1.9,n.y+.48,n.z-Math.sin(n.yaw)*side*1.9,.18,.95,.18,n.yaw);}}
 for(const d of section.decorations){if(d.kind==='tree'){const h=d.scale,key=d.variant===1?'LEAVES_LIGHT':'LEAVES';if(lod===2){const x=d.x-section.entryTransform.x,z=d.z-section.entryTransform.z,base=d.y,top=base+h*1.5;triangle('FOREST_FAR',[x-h*.35,base+h*.35,z],[x,top,z],[x+h*.35,base+h*.35,z]);triangle('FOREST_FAR',[x,base+h*.35,z-h*.35],[x,top,z],[x,base+h*.35,z+h*.35]);}else{boxPiece('TRUNK',d.x,d.y+h/2,d.z,.25,h,.25,d.rotation);boxPiece(key,d.x,d.y+h*.8,d.z,h*.6,h*.5,h*.6,d.rotation);if(lod===0){boxPiece(key,d.x,d.y+h*1.08,d.z,h*.38,h*.4,h*.38,d.rotation+.4);if(d.variant===2)boxPiece(key,d.x,d.y+h*1.3,d.z,h*.21,h*.3,h*.21,d.rotation);}}}else if(lod===0)boxPiece(d.kind==='stone'?'STONE':'LEAVES_LIGHT',d.x,d.y+d.scale*.4,d.z,d.scale,d.scale*.8,d.scale,d.rotation);}

 const keys=new Set([...Object.keys(terrainColors),...Object.keys(slot),...Object.keys(batches)]);for(const key of keys){if(decorOnly&&!['TRUNK','LEAVES','LEAVES_LIGHT','STONE','FOREST_FAR'].includes(key))continue;if(!terrainColors[key])continue;const data=batches[key]||{v:[],n:[]};slot[key]=uploadGeometry(data.v,data.n,slot[key],data.uv);}slot._section=section;slot._lod=lod;slot._revision=section.decorationRevision;return slot;
}
function syncWorldMeshes(pos=world.locate(physics.p[0],physics.p[2]).s){for(const [id,slot] of chunkSlots)if(!world.sections.some(s=>s.id===id)){chunkSlots.delete(id);freeSlots.push(slot);}for(const section of world.sections){const lod=chunkLOD(section,pos);if(!chunkSlots.has(section.id))chunkSlots.set(section.id,buildChunk(section,freeSlots.pop(),lod));else{const slot=chunkSlots.get(section.id);if(slot._section!==section)buildChunk(section,slot,lod);else if(slot._lod!==lod||slot._revision!==section.decorationRevision)buildChunk(section,slot,lod,true);}}}

const terrainColors={WOOD:[.47,.34,.20],PIT:[.34,.29,.22],HAZARD_ROCK:[.73,.69,.58],EARTH_BUMP:[.72,.57,.36],FOREST_FAR:[.25,.37,.29],ROCK:[.55,.54,.46],GRASS:[.43,.53,.36],DIRT:[.64,.59,.44],SOFT_DIRT:[.55,.44,.30],MUD:[.31,.27,.19],WATER:[.37,.35,.26],WATER_TOP:[.37,.53,.53],TRUNK:[.34,.27,.20],LEAVES:[.22,.36,.25],LEAVES_LIGHT:[.30,.43,.28],STONE:[.48,.50,.44]};syncWorldMeshes();
const car={x:spawn.x,z:spawn.z,a:spawn.yaw,v:0,steer:0,y:spawn.y+.15},keys=new Set(),joy={x:0,y:0,id:null},look={x:0,y:0,id:null},orbit={yaw:0,elevation:CAMERA_CONFIG.chaseElevation,distance:CAMERA_CONFIG.chaseDistance,idle:0},pedals={gas:0,brake:false};
function bindStick(selector,knobSelector,state,steeringOnly=false){const pad=document.querySelector(selector),knob=document.querySelector(knobSelector);function move(e){const r=pad.getBoundingClientRect(),radius=r.width*.35;let x=e.clientX-r.left-r.width/2,y=steeringOnly?0:e.clientY-r.top-r.height/2;const d=Math.hypot(x,y);if(d>radius){x*=radius/d;y*=radius/d;}state.x=x/radius;state.y=-y/radius;knob.style.transform=`translate(${x}px,${y}px)`;e.preventDefault();}function reset(){state.id=null;state.x=state.y=0;knob.style.transform='';}pad.addEventListener('pointerdown',e=>{if(state.id!==null)return;state.id=e.pointerId;pad.setPointerCapture(e.pointerId);move(e);});pad.addEventListener('pointermove',e=>{if(state.id===e.pointerId)move(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(event,e=>{if(e.pointerId===state.id)reset();});return reset;}
const release=bindStick('#stick','#knob',joy,true),lookRelease=()=>{look.id=null;look.x=look.y=0;};
const pedalResets=[bindThrottle(document.querySelector('#gas'),value=>pedals.gas=value)];const brakeButton=document.querySelector('#brake');let brakePointer=null;pedalResets.push(()=>{brakePointer=null;pedals.brake=false;brakeButton.classList.remove('active');});brakeButton.addEventListener('pointerdown',e=>{if(brakePointer!==null)return;brakePointer=e.pointerId;pedals.brake=true;brakeButton.setPointerCapture(e.pointerId);brakeButton.classList.add('active');e.preventDefault();});for(const event of ['pointerup','pointercancel','lostpointercapture'])brakeButton.addEventListener(event,e=>{if(e.pointerId===brakePointer){brakePointer=null;pedals.brake=false;brakeButton.classList.remove('active');}});
let cameraMode='CHASE',cameraSnap=false;const hood=new HoodCamera(visual);document.querySelector('#cam').addEventListener('click',()=>{cameraMode=cameraMode==='CHASE'?'HOOD':'CHASE';document.querySelector('#cam').classList.toggle('active',cameraMode==='HOOD');document.querySelector('#cam').setAttribute('aria-pressed',String(cameraMode==='HOOD'));releaseFloating();drag=null;hood.reset(visual);cameraSnap=true;});
// Invisible floating camera control, independent from steering and pedals.
let cameraTouch=null;function releaseFloating(){if(!cameraTouch)return;cameraTouch=null;lookRelease();}canvas.addEventListener('pointerdown',e=>{if(cameraMode==='CHASE'&&e.pointerType==='touch'&&e.clientX>=innerWidth/2&&look.id===null){look.id=e.pointerId;cameraTouch={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);e.preventDefault();}});canvas.addEventListener('pointermove',e=>{if(cameraTouch?.id===e.pointerId){let x=e.clientX-cameraTouch.x,y=e.clientY-cameraTouch.y,d=Math.hypot(x,y);if(d>40){x*=40/d;y*=40/d;}look.x=-x/40;look.y=y/40;e.preventDefault();}});for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{if(cameraTouch?.id===e.pointerId)releaseFloating();});
let drag=null;canvas.addEventListener('pointerdown',e=>{if(cameraMode==='CHASE'&&e.pointerType==='mouse'&&e.clientX>=innerWidth/2){drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(drag&&drag.id===e.pointerId){orbit.yaw-=(e.clientX-drag.x)*.008;orbit.elevation=Math.max(.12,Math.min(1.12,orbit.elevation-(drag.y-e.clientY)*.006));orbit.idle=0;drag.x=e.clientX;drag.y=e.clientY;}});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(drag?.id===e.pointerId)drag=null;});
let focus=[spawn.x,spawn.y+1.2,spawn.z];function orbitTarget(dt){const active=look.id!==null||drag!==null;if(active)orbit.idle=0;else orbit.idle+=dt;orbit.yaw+=(Math.abs(look.x)>.08?look.x:0)*1.9*dt;orbit.yaw=Math.atan2(Math.sin(orbit.yaw),Math.cos(orbit.yaw));orbit.elevation=Math.max(.12,Math.min(1.12,orbit.elevation+(Math.abs(look.y)>.08?look.y:0)*1.05*dt));if(orbit.idle>1.6){const blend=1-Math.exp(-1.6*dt);orbit.yaw*=1-blend;orbit.elevation+=(CAMERA_CONFIG.chaseElevation-orbit.elevation)*blend;}focus=focus.map((v,i)=>v+([car.x,car.y+1.05,car.z][i]-v)*(1-Math.exp(-(i===1?3:8)*dt)));const angle=car.a+orbit.yaw,r=(orbit.distance+Math.max(-.15,Math.min(.30,physics.state.longitudinalAcceleration*CAMERA_CONFIG.accelerationOffset)))*Math.cos(orbit.elevation),x=focus[0]-Math.sin(angle)*r,z=focus[2]-Math.cos(angle)*r;return[x,Math.max(focus[1]+orbit.distance*Math.sin(orbit.elevation),height(x,z)+.9),z];}
const allowed=['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'];window.addEventListener('keydown',e=>{if(allowed.includes(e.code)){keys.add(e.code);e.preventDefault();}});window.addEventListener('keyup',e=>keys.delete(e.code));function clear(){keys.clear();releaseFloating();release();lookRelease();drag=null;handHeld=false;pedalResets.forEach(reset=>reset());for(const id of ['#gas','#brake'])document.querySelector(id).classList.remove('active');}window.addEventListener('blur',clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();});
let handHeld=false,hudTime=0;function step(dt){const drive=(pedals.brake||keys.has('KeyS')||keys.has('ArrowDown'))?-1:(keys.has('KeyW')||keys.has('ArrowUp')?1:pedals.gas);const steer=Math.abs(joy.x)>.08?joy.x:+(keys.has('KeyD')||keys.has('ArrowRight'))-+(keys.has('KeyA')||keys.has('ArrowLeft'));physics.advance(dt,{drive,steer,handbrake:handHeld||keys.has('Space')});const roadPoint=world.update(physics.p[0],physics.p[2]);if(Math.abs(roadPoint.lateral)>34){const side=Math.sign(roadPoint.lateral);physics.p[0]=roadPoint.x+Math.cos(roadPoint.yaw)*34*side;physics.p[2]=roadPoint.z-Math.sin(roadPoint.yaw)*34*side;physics.v[0]*=.9;physics.v[2]*=.9;}if(Math.abs(physics.p[2])>1000){const dx=physics.p[0],dz=physics.p[2];world.shift(dx,dz);physics.p[0]-=dx;physics.p[2]-=dz;physics.previousPose=null;visual.reset();hood.p[0]-=dx;hood.p[2]-=dz;focus[0]-=dx;focus[2]-=dz;camera[0]-=dx;camera[2]-=dz;}syncWorldMeshes();visual.update(dt);const origin=visual.matrix;car.x=origin[12];car.y=origin[13];car.z=origin[14];car.a=visual.yaw;car.steer=physics.steer;car.v=physics.state.vehicleSpeed/3.6;sound.update(physics.state);hudTime+=dt;if(hudTime>=.1){updateHUD();hudTime=0;}}
function rotateX(a){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([1,0,0,0,0,c,s,0,0,-s,c,0,0,0,0,1]);}function rotateZ(a){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,s,0,0,-s,c,0,0,0,0,1,0,0,0,0,1]);}
// Reference-built low-poly Niva. Coordinates in metres, nose at +Z.
function polygonMesh(points){const vv=[],nn=[];for(let i=1;i<points.length-1;i++){const a=points[0],b=points[i],c=points[i+1],normal=norm(cross(b.map((v,j)=>v-a[j]),c.map((v,j)=>v-a[j])));for(const p of [a,b,c]){vv.push(...p);nn.push(...normal);}}return mesh(vv,nn);}
function extrude(profile,width){function half(p){return width/2-(width>1.65?Math.max(0,p[0]-1.60)*.22+Math.max(0,-p[0]-1.66)*.20:0);}const vv=[],nn=[];function tri(a,b,c){const normal=norm(cross(b.map((v,j)=>v-a[j]),c.map((v,j)=>v-a[j])));for(const p of [a,b,c]){vv.push(...p);nn.push(...normal);}}
// Ear clipping preserves the concave openings over all four tyres.
let ids=profile.map((_,i)=>i);const area=profile.reduce((s,p,i)=>{const q=profile[(i+1)%profile.length];return s+p[0]*q[1]-q[0]*p[1];},0),sign=Math.sign(area);const cross2=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);const inside=(p,a,b,c)=>sign*cross2(a,b,p)>=-1e-8&&sign*cross2(b,c,p)>=-1e-8&&sign*cross2(c,a,p)>=-1e-8;let guard=0;while(ids.length>2&&guard++<500){let found=false;for(let j=0;j<ids.length;j++){const ia=ids[(j+ids.length-1)%ids.length],ib=ids[j],ic=ids[(j+1)%ids.length],a=profile[ia],b=profile[ib],c=profile[ic];if(sign*cross2(a,b,c)<=1e-8)continue;if(ids.some(k=>k!==ia&&k!==ib&&k!==ic&&inside(profile[k],a,b,c)))continue;for(const side of [-1,1])tri([side*half(a),a[1],a[0]],[side*half(b),b[1],b[0]],[side*half(c),c[1],c[0]]);ids.splice(j,1);found=true;break;}if(!found)throw Error('Car profile triangulation failed');}
for(let i=0;i<profile.length;i++){const a=profile[i],b=profile[(i+1)%profile.length],p=[-half(a),a[1],a[0]],q=[half(a),a[1],a[0]],r=[half(b),b[1],b[0]],t=[-half(b),b[1],b[0]];tri(p,q,r);tri(p,r,t);}return mesh(vv,nn);}
const lower=[[-1.82,.53]];for(const centre of [-1.1,1.1]){const radius=.51,start=Math.asin((.53-.44)/radius);for(let i=0;i<=14;i++){const a=Math.PI-start-(Math.PI-2*start)*i/14;lower.push([centre+radius*Math.cos(a),.44+radius*Math.sin(a)]);}}lower.push([1.82,.53],[1.84,1.06],[1.77,1.145],[.75,1.185],[.55,1.17],[-1.81,1.09]);
const shell=extrude(lower,1.68),cabin=extrude([[-1.81,1.085],[-1.43,1.70],[.17,1.70],[.75,1.18]],1.58);
function sheet(xs,zs,top,side,warp=(x,z)=>z){const pt=(x,z,y)=>[x,y,warp(x,z)];const v=[],n=[];function triangle(a,b,c){const normal=norm(cross(b.map((v,i)=>v-a[i]),c.map((v,i)=>v-a[i])));for(const p of [a,b,c]){v.push(...p);n.push(...normal);}}
for(let j=0;j<zs.length-1;j++)for(let i=0;i<xs.length-1;i++){const a=pt(xs[i],zs[j],top(xs[i],zs[j])),b=pt(xs[i+1],zs[j],top(xs[i+1],zs[j])),c=pt(xs[i+1],zs[j+1],top(xs[i+1],zs[j+1])),d=pt(xs[i],zs[j+1],top(xs[i],zs[j+1]));triangle(a,d,b);triangle(b,d,c);}
for(const x of [xs[0],xs.at(-1)])for(let j=0;j<zs.length-1;j++){const a=pt(x,zs[j],top(x,zs[j])),b=pt(x,zs[j+1],top(x,zs[j+1])),c=pt(x,zs[j+1],side(x,zs[j+1])),d=pt(x,zs[j],side(x,zs[j]));triangle(a,b,c);triangle(a,c,d);}
for(const z of [zs[0],zs.at(-1)])for(let i=0;i<xs.length-1;i++){const a=pt(xs[i],z,top(xs[i],z)),b=pt(xs[i+1],z,top(xs[i+1],z)),c=pt(xs[i+1],z,side(xs[i+1],z)),d=pt(xs[i],z,side(xs[i],z));triangle(a,b,c);triangle(a,c,d);}return mesh(v,n);}
function roofTop(x,z){const across=Math.max(0,1-(x/.815)**2),along=Math.max(0,1-((z+.59)/.89)**4);return 1.704+.09*across+.015*along;}
const roof=sheet([-.815,-.74,-.50,0,.50,.74,.815],[-1.46,-1.37,-1.05,-.55,-.05,.14,.24],roofTop,()=>1.69,(x,z)=>z-(z+.61)*.10*(Math.abs(x)/.815)**6);
function bonnetTop(x,z){return 1.185-(z-.72)*.045+.034*Math.max(0,1-(x/.79)**2);}
const bonnet=sheet([-.79,-.72,-.42,0,.42,.72,.79],[.72,.81,1.22,1.65,1.77,1.83],bonnetTop,(x,z)=>z>1.75?1.065:1.15);
const glazing=[];function panel(points,color){glazing.push({shape:polygonMesh(points),color});}
const green=[.20,.32,.30],dark=[.075,.095,.085],rubber=[.105,.115,.105],glass=[.24,.36,.38],chrome=[.65,.68,.65];
for(const side of [-1,1]){const x=side*.795;
panel([[x,1.16,-1.63],[x,1.47,-1.52],[x,1.65,-1.33],[x,1.65,-.48],[x,1.16,-.48]],dark);
panel([[x+side*.002,1.20,-1.58],[x+side*.002,1.47,-1.47],[x+side*.002,1.60,-1.30],[x+side*.002,1.60,-.53],[x+side*.002,1.20,-.53]],glass);
panel([[x,1.225,-.40],[x,1.65,-.40],[x,1.65,.12],[x,1.225,.57]],dark);
panel([[x+side*.002,1.26,-.35],[x+side*.002,1.60,-.35],[x+side*.002,1.60,.105],[x+side*.002,1.26,.50]],glass);
// Small triangular vent window, separated by a thin frame.
panel([[x+side*.004,1.24,.32],[x+side*.004,1.44,.32],[x+side*.004,1.24,.55]],dark);
panel([[x+side*.006,1.265,.355],[x+side*.006,1.405,.355],[x+side*.006,1.265,.495]],glass);
}
function frontPlane(y,offset=0){return .75-(y-1.18)*.58/.52+offset;}
const windOutline=[[-.71,1.235],[.71,1.235],[.71,1.615],[.665,1.666],[-.665,1.666],[-.71,1.615]];
const windGlass=[[-.678,1.263],[.678,1.263],[.678,1.604],[.645,1.639],[-.645,1.639],[-.678,1.604]];
panel(windOutline.map(([x,y])=>[x,y,frontPlane(y,.01)]),dark);
panel(windGlass.map(([x,y])=>[x,y,frontPlane(y,.015)]),glass);
// Rear glass and trim share one plane, offset slightly from the tailgate.
// The previous non-planar fan intersected the crease in the rear body surface.
function rearPlane(y,offset=0){return -1.81+(y-1.085)*.38/.615-offset;}
const rearOutline=[[-.70,1.20],[.70,1.20],[.70,1.57],[.63,1.65],[-.63,1.65],[-.70,1.57]];
const rearGlass=[[-.665,1.235],[.665,1.235],[.665,1.555],[.614,1.615],[-.614,1.615],[-.665,1.555]];
panel(rearOutline.map(([x,y])=>[x,y,rearPlane(y,.009)]),dark);
panel(rearGlass.map(([x,y])=>[x,y,rearPlane(y,.014)]),glass);
const archDetails=[];for(const side of [-1,1])for(const centre of [-1.1,1.1])for(let i=0;i<18;i++){const a=.18+i*(Math.PI-.36)/18,b=.18+(i+1)*(Math.PI-.36)/18;const points=[];for(const [angle,radius] of [[a,.512],[b,.512],[b,.555],[a,.555]])points.push([side*.846,.44+Math.sin(angle)*radius,centre+Math.cos(angle)*radius]);archDetails.push(polygonMesh(points));}
function linePart(a,b,width,color){const direction=norm(b.map((v,i)=>v-a[i])),right=norm(cross(direction,Math.abs(direction[1])>.9?[1,0,0]:[0,1,0])),up=cross(direction,right),length=Math.hypot(...b.map((v,i)=>v-a[i])),mid=a.map((v,i)=>(v+b[i])/2);const m=new Float32Array([...right.map(v=>v*width),0,...up.map(v=>v*width),0,...direction.map(v=>v*length),0,...mid,1]);draw(cube,mul(body,m),color);}
let body;function part(x,y,z,sx,sy,sz,col){draw(cube,mul(body,matrix(x,y,z,sx,sy,sz)),col);}const facing=new Float32Array([1,0,0,0,0,0,1,0,0,-1,0,0,0,0,0,1]);function roundPart(x,y,z,r,depth,col){draw(cylinder,mul(mul(body,matrix(x,y,z,1,1,1)),mul(facing,matrix(0,0,0,r,depth,r))),col);}
function vehicle(){body=visual.matrix;draw(shell,body,green);draw(cabin,body,green);draw(roof,body,green);draw(bonnet,body,green);for(const panel of glazing)draw(panel.shape,body,panel.color);
part(0,.49,0,1.32,.12,2.6,dark);
// Thin arch mouldings, roof gutters, bonnet stampings and wipers.
for(const arch of archDetails)draw(arch,body,[.23,.32,.28]);
for(const side of [-1,1]){linePart([side*.82,1.699,-1.35],[side*.82,1.699,.12],.018,chrome);linePart([side*.66,bonnetTop(side*.66,.81)+.004,.81],[side*.66,bonnetTop(side*.66,1.68)+.004,1.68],.012,[.29,.38,.33]);linePart([side*.44,1.276,frontPlane(1.276,.027)],[side*.16,1.301,frontPlane(1.301,.027)],.014,dark);linePart([side*.838,1.14,.74],[side*.838,1.12,1.72],.01,dark);part(side*.845,1.08,.96,.009,.055,.14,[.76,.47,.16]);}
// Tailgate perimeter, rear wiper, vents and small licence plates.
linePart([-.73,.71,-1.837],[.73,.71,-1.837],.013,dark);for(const side of [-1,1])linePart([side*.73,.72,-1.837],[side*.73,1.12,-1.837],.013,dark);linePart([.03,1.245,rearPlane(1.245,.025)],[.34,1.27,rearPlane(1.27,.025)],.016,dark);part(0,.648,1.989,.40,.083,.014,[.81,.81,.72]);
for(const side of [-1,1])for(let i=0;i<3;i++)part(side*.803,1.43+i*.039,-1.59,.014,.012,.09,dark);
// Door outlines and recognisable body crease under the glazing.
for(const side of [-1,1]){const x=side*.843;part(x,1.10,-.55,.009,.012,2.32,[.30,.38,.34]);part(x,.80,-.44,.009,.53,.012,dark);part(x,.72,.57,.009,.27,.012,dark);part(x,.548,.03,.009,.012,.9,dark);part(x,1.025,-.24,.025,.035,.15,chrome);part(side*.86,1.23,.52,.11,.028,.035,dark);part(side*.925,1.275,.52,.12,.12,.07,dark);}
// Round lamps, rectangular indicators, narrow grille and plain bumpers.
for(const x of [-.645,.645]){roundPart(x,.93,1.852,.285,.018,dark);roundPart(x,.93,1.873,.237,.023,[.88,.87,.70]);roundPart(x-.035,.970,1.889,.065,.01,[.97,.97,.88]);part(x,1.112,1.842,.25,.067,.025,dark);part(x,1.115,1.860,.20,.043,.018,[.90,.67,.30]);part(x,.85,-1.833,.17,.27,.025,dark);part(x,.91,-1.849,.135,.13,.018,[.69,.19,.12]);part(x,.807,-1.849,.135,.055,.018,[.93,.61,.25]);}
part(0,.86,1.855,.89,.25,.019,dark);for(let i=0;i<4;i++)part(0,.77+i*.057,1.873,.85,.012,.016,chrome);for(let i=-3;i<=3;i++)part(i*.105,.855,1.877,.014,.22,.012,[.32,.37,.34]);part(0,.87,1.896,.055,.075,.01,chrome);
for(const z of [-1.90,1.91]){part(0,.64,z,1.83,.10,.13,chrome);for(const x of [-.61,.61])part(x,.64,z+(z>0?.077:-.077),.11,.16,.025,dark);}
part(0,.77,-1.847,.43,.13,.02,dark);part(0,.773,-1.863,.36,.083,.012,[.83,.83,.75]);part(0,1.04,-1.831,.14,.03,.025,chrome);
// Steel rims with small circular holes; no spinning rectangles outside tyres.
// Rear beam follows both independent wheel contacts.
const left=visual.wheels[2].position,right=visual.wheels[3].position,beam=norm(right.map((v,i)=>v-left[i])),beamUp=norm(cross(rotate(visual.q,[0,0,1]),beam)),beamSide=cross(beam,beamUp),mid=left.map((v,i)=>(v+right[i])/2);draw(cube,new Float32Array([...beam.map(v=>v*1.70),0,...beamUp.map(v=>v*.12),0,...beamSide.map(v=>v*.12),0,...mid,1]),dark);
for(const w of visual.wheels){const up=rotate(visual.q,[0,1,0]),localForward=rotate(visual.q,[Math.sin(w.steer),0,Math.cos(w.steer)]),axis=w.front?norm(cross(up,localForward)):beam,wheelUp=norm(cross(localForward,axis));let m=new Float32Array([...axis,0,...wheelUp,0,...localForward,0,...w.position.map((v,i)=>v-(i===1?w.visualSink||0:0)),1]);m=mul(m,rotateX(w.angle));const axle=(diameter,width)=>new Float32Array([0,diameter,0,0,-width,0,0,0,0,0,diameter,0,0,0,0,1]);draw(cylinder,mul(m,axle(CAR_CONFIG.wheelRadius*2,.25)),rubber);draw(cylinder,mul(m,axle(.53,.259)),chrome);draw(cylinder,mul(m,axle(.17,.275)),[.40,.44,.41]);for(let i=0;i<6;i++){const a=i*Math.PI/3,local=matrix(Math.sign(w.x)*.134,Math.cos(a)*.18,Math.sin(a)*.18,1,1,1);draw(cylinder,mul(m,mul(local,axle(.075,.008))),dark);}}}
const hud={gear:document.querySelector('#gear'),rpm:document.querySelector('#rpm'),range:document.querySelector('#range'),center:document.querySelector('#center-lock'),rear:document.querySelector('#rear-lock'),wheels:document.querySelector('#wheel-status')};
function updateHUD(){const s=physics.state;hud.gear.textContent=(s.currentGear<0?'R':s.currentGear)+' | '+s.transferRange+' | 4WD'+(s.centerLocked?' · C':'')+(s.rearLocked?' · R':'')+((s.pendingRange||s.pendingCenter||s.pendingRear)?' · WAIT':'');hud.rpm.textContent=Math.round(s.currentRPM)+' RPM';hud.range.textContent=s.pendingRange?'H/L · WAIT':'H/L · '+s.transferRange;hud.center.textContent=s.pendingCenter?'C LOCK · WAIT':'C LOCK '+(s.centerLocked?'ON':'OFF');hud.rear.textContent=s.pendingRear?'R LOCK · WAIT':'R LOCK '+(s.rearLocked?'ON':'OFF');hud.center.classList.toggle('active',s.centerLocked);hud.rear.classList.toggle('active',s.rearLocked);hud.range.classList.toggle('active',s.transferRange==='L');hud.center.setAttribute('aria-pressed',String(s.centerLocked));hud.rear.setAttribute('aria-pressed',String(s.rearLocked));document.querySelector('#surface').textContent=[...new Set(physics.wheels.filter(w=>w.contact).map(w=>w.surfaceType||'DIRT'))].join(' / ');if(!transmissionPanel.hidden)hud.wheels.innerHTML=physics.wheels.map(w=>`<i class="${w.contact&&w.load>100?'contact':'air'}" title="${w.id}: ${Math.round(w.load)} N">${w.id} ${w.surfaceType||'DIRT'}${Math.abs(w.slipRatio)>.22&&w.contact?' ↻':''}</i>`).join('');}
hud.range.addEventListener('click',()=>physics.requestRange());hud.center.addEventListener('click',()=>physics.requestCenter());hud.rear.addEventListener('click',()=>physics.requestRear());const hand=document.querySelector('#handbrake');hand.addEventListener('pointerdown',e=>{handHeld=true;hand.setPointerCapture(e.pointerId);hand.classList.add('active');e.preventDefault();});for(const type of ['pointerup','pointercancel','lostpointercapture'])hand.addEventListener(type,()=>{handHeld=false;hand.classList.remove('active');});document.querySelector('#reset').addEventListener('click',()=>resetToRoad());
const transmissionPanel=document.querySelector('#transmission-panel'),toggle=document.querySelector('#transmission');transmissionPanel.hidden=true;toggle.addEventListener('click',()=>{transmissionPanel.hidden=!transmissionPanel.hidden;toggle.setAttribute('aria-expanded',String(!transmissionPanel.hidden));});
function resetToRoad(section=world.current,u=.15){clear();const p=world.point(section,u);physics.reset(p.x,p.z,p.yaw);physics.previousPose=null;visual.reset();hood.reset(visual);cameraSnap=true;orbit.yaw=0;orbit.elevation=CAMERA_CONFIG.chaseElevation;focus=[p.x,p.y+1.2,p.z];camera=[p.x-Math.sin(p.yaw)*8,p.y+5,p.z-Math.cos(p.yaw)*8];world.update(p.x,p.z);syncWorldMeshes();}
const debugPanel=document.querySelector('#debug-panel');debugPanel.hidden=!debug;document.querySelector('#next-section').addEventListener('click',()=>{const next=world.sections.find(s=>s.id===world.current.id+1);if(next)resetToRoad(next);});document.querySelector('#regenerate').addEventListener('click',()=>{world.reset(world.seed);resetToRoad(world.sections[0],18/world.sections[0].length);});let measuredFPS=60;function updateDebug(){if(debug)document.querySelector('#debug-info').textContent=`${world.current.mode} · ${world.current.type} #${world.current.id+1} · SEED ${world.seed} · ${world.sections.length} секций · ${Math.round(measuredFPS)} FPS · ${Math.round(physics.state.vehicleSpeed)} км/ч · G ${physics.state.currentGear} · ${Math.round(physics.state.currentRPM)} RPM · ${physics.state.shiftEventTime?physics.state.shiftEvent: ''} · THR ${Math.round(physics.state.throttle*100)}% · ${cameraMode} · R LOCK ${physics.state.rearLocked?'ON':'OFF'} · SPLIT ${(100*(physics.state.torqueSplit?.[0]??.5)).toFixed(0)}/${(100*(physics.state.torqueSplit?.[1]??.5)).toFixed(0)} · ${physics.wheels.map(w=>w.id+':'+w.surfaceType).join(' ')} · X ${(physics.p[0]+world.offset[0]).toFixed(1)} Z ${(physics.p[2]+world.offset[1]).toFixed(1)}`;document.querySelector('#distance').textContent=Math.floor(world.distance)+' м';const next=world.sections.find(s=>s.id===world.current.id+1);document.querySelector('#road-warning').textContent=world.current.type==='BRAKING_ZONE'?'ТОРМОЗИ · '+(next?.type||'TECH'):world.current.mode==='TECH'?'TECH · '+world.current.type:'';}

let portraitPaused=false;
function updateOrientation(){const portrait=!!window.matchMedia?.('(orientation: portrait) and (pointer: coarse)').matches;if(portrait!==portraitPaused){clear();portraitPaused=portrait;}document.querySelector('#rotate-hint').setAttribute('aria-hidden',String(!portrait));}
window.addEventListener('resize',updateOrientation);window.addEventListener('orientationchange',updateOrientation);updateOrientation();
document.querySelector('#fullscreen').addEventListener('click',async()=>{try{if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();}catch{}try{if(window.screen?.orientation?.lock)await window.screen.orientation.lock('landscape');}catch{}});
let camera=[spawn.x,spawn.y+5.2,spawn.z+8.7],last=0;gl.enable(gl.DEPTH_TEST);gl.clearColor(.73,.79,.74,1);const speed=document.querySelector('#speed'),gear=document.querySelector('#gear');function frame(t){const rawDt=(t-last)/1000||.016,dt=Math.min(rawDt,.05);last=t;measuredFPS+=(1/Math.max(.001,rawDt)-measuredFPS)*.05;if(!portraitPaused)step(dt);const target=orbitTarget(dt),hoodView=hood.update(dt,visual,cameraSnap);camera=cameraSnap?target:camera.map((v,i)=>v+(target[i]-v)*(1-Math.exp(-CAMERA_CONFIG.chaseFollow*dt)));camera[1]=Math.max(camera[1],height(camera[0],camera[2])+.7);cameraSnap=false;const dpr=Math.min(devicePixelRatio||1,1.5),w=Math.round(innerWidth*dpr),h=Math.round(innerHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h);}const eye=cameraMode==='HOOD'?hoodView.eye:camera,aim=cameraMode==='HOOD'?hoodView.target:focus,up=cameraMode==='HOOD'?hoodView.up:[0,1,0],f=1/Math.tan((cameraMode==='HOOD'?CAMERA_CONFIG.hoodFov:CAMERA_CONFIG.chaseFov)*Math.PI/360),near=.06,far=650;pv=mul(new Float32Array([f/(w/h),0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]),view(eye,aim,up));gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniform3fv(loc.eye,eye);const roadS=world.locate(physics.p[0],physics.p[2]).s;for(const slot of chunkSlots.values()){const section=slot._section,dist=Math.max(0,section.startDistance-roadS,roadS-section.startDistance-section.length);if(dist>VIEW_CONFIG.drawDistance)continue;const model=matrix(section.entryTransform.x,0,section.entryTransform.z,1,1,1);for(const [key,shape] of Object.entries(slot))if(terrainColors[key]&&shape.count)draw(shape,model,terrainColors[key],key==='DIRT'||key==='SOFT_DIRT'?1:key==='MUD'||key==='PIT'?2:key==='WOOD'?3:key==='WATER_TOP'?4:0);}vehicle();updateDebug();speed.textContent=Math.round(Math.abs(car.v)*3.6);requestAnimationFrame(frame);}canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();clear();document.querySelector('#error').hidden=false;document.querySelector('#error').textContent='3D-контекст потерян. Перезагрузи страницу.';});requestAnimationFrame(frame);
export {hood,cameraMode,physics,visual,world,height,groundNormal,grip,sampleSurface,orbit,pedals,chunkSlots,freeSlots,resetToRoad};
