import {sampleSurface,SURFACE_PATCHES} from './surfaces.js?v=0063';
import {OffroadVehicle,CAR_CONFIG,rotate} from './physics.js?v=0063';
import {EngineAudio} from './engine-audio.js?v=0063';
const canvas=document.querySelector('canvas'),gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl){document.querySelector('#error').hidden=false;document.querySelector('#error').textContent='WebGL недоступен. Открой сайт в Safari или Chrome.';throw Error('WebGL unavailable');}
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,`attribute vec3 p;attribute vec3 n;uniform mat4 mvp;uniform mat4 model;varying float light;varying float fog;void main(){light=.6+.4*max(dot(normalize(mat3(model)*n),normalize(vec3(-.5,1.,.3))),0.);gl_Position=mvp*vec4(p,1.);fog=gl_Position.w;}`));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float;uniform vec3 color;varying float light;varying float fog;void main(){gl_FragColor=vec4(mix(color*light,vec3(.73,.79,.74),smoothstep(50.,140.,fog)),1.);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);const loc={};for(const k of ['mvp','model','color'])loc[k]=gl.getUniformLocation(program,k);for(const k of ['p','n'])loc[k]=gl.getAttribLocation(program,k);
function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function matrix(x,y,z,sx,sy,sz,a=0){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c*sx,0,-s*sx,0,0,sy,0,0,s*sz,0,c*sz,0,x,y,z,1]);}
function norm(v){const d=Math.hypot(...v)||1;return v.map(x=>x/d);}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}function dot(a,b){return a.reduce((s,v,i)=>s+v*b[i],0);}function view(e,t){const z=norm(e.map((v,i)=>v-t[i])),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1]);}
function mesh(v,n){function buf(data){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);return b;}return{p:buf(v),n:buf(n),count:v.length/3};}
const v=[],n=[];for(let axis=0;axis<3;axis++)for(const sign of [-1,1]){const corners=[];for(const [u,w] of [[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]]){const p=[0,0,0];p[axis]=sign*.5;p[(axis+1)%3]=u;p[(axis+2)%3]=w;corners.push(p);}const normal=[0,0,0];normal[axis]=sign;for(const i of [0,1,2,0,2,3]){v.push(...corners[i]);n.push(...normal);}}const cube=mesh(v,n);
const rv=[],rn=[];for(let i=0;i<12;i++){const a=i*Math.PI/6,b=(i+1)*Math.PI/6;const points=[[Math.cos(a)*.5,-.5,Math.sin(a)*.5],[Math.cos(b)*.5,-.5,Math.sin(b)*.5],[Math.cos(b)*.5,.5,Math.sin(b)*.5],[Math.cos(a)*.5,.5,Math.sin(a)*.5]];for(const j of [0,1,2,0,2,3]){rv.push(...points[j]);rn.push(Math.cos((a+b)/2),0,Math.sin((a+b)/2));}for(const y of [-.5,.5])for(const p of [[0,y,0],[Math.cos(a)*.5,y,Math.sin(a)*.5],[Math.cos(b)*.5,y,Math.sin(b)*.5]]){rv.push(...p);rn.push(0,Math.sign(y),0);}}const cylinder=mesh(rv,rn);
let pv;function draw(shape,m,col){for(const k of ['p','n']){gl.bindBuffer(gl.ARRAY_BUFFER,shape[k]);gl.vertexAttribPointer(loc[k],3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(loc[k]);}gl.uniformMatrix4fv(loc.model,false,m);gl.uniformMatrix4fv(loc.mvp,false,mul(pv,m));gl.uniform3fv(loc.color,col);gl.drawArrays(gl.TRIANGLES,0,shape.count);}
// Fixed test terrain: broad hills, a hollow and a gentle starting area.
function baseHeight(x,z){const fade=1-Math.exp(-(x*x+(z-4)*(z-4))/700);return fade*(1.5*Math.sin(x*.065)*Math.cos(z*.055)+4.5*Math.exp(-((x-29)**2+(z+30)**2)/260)+3.8*Math.exp(-((x+28)**2+(z+39)**2)/200)-2.6*Math.exp(-((x+17)**2+(z-29)**2)/190));}
const grid=1,min=-80,count=160,stride=count+1,heights=[];for(let z=0;z<=count;z++)for(let x=0;x<=count;x++)heights.push(baseHeight(min+x*grid,min+z*grid));
function baseSample(x,z){const fx=Math.max(0,Math.min(count-.00001,(x-min)/grid)),fz=Math.max(0,Math.min(count-.00001,(z-min)/grid)),ix=Math.floor(fx),iz=Math.floor(fz),u=fx-ix,w=fz-iz;const a=heights[iz*stride+ix],b=heights[iz*stride+ix+1],c=heights[(iz+1)*stride+ix],d=heights[(iz+1)*stride+ix+1];return u+w<=1?a+(b-a)*u+(c-a)*w:d+(c-d)*(1-u)+(b-d)*(1-w);}
const smooth=x=>{x=Math.max(0,Math.min(1,x));return x*x*(3-2*x);};
function obstacles(x,z){let diagonal=0;for(const [cx,cz] of [[9.15,-5.8],[10.85,-8.04],[9.15,-10.4],[10.85,-12.64]])diagonal+=.34*Math.exp(-((x-cx)**2/.65+(z-cz)**2/.85));const lane=smooth((3-Math.abs(x+12))/1.2),rise=smooth((-z-4)/9),fall=smooth((z+31)/10);const pit=smooth((x-18)/1.5)*smooth((26-x)/1.5)*smooth((-z-9)/2)*smooth((z+30)/2),ford=smooth((x-28)/1.5)*smooth((36-x)/1.5)*smooth((-z-9)/2)*smooth((z+24)/2);return diagonal+lane*3*rise*fall-.055*pit-.12*ford;}
const zones=[{x0:7,x1:13,z0:-15,z1:-3,step:.20,color:[.60,.55,.43]},{x0:-16,x1:-8,z0:-32,z1:-2,step:.25,color:[.55,.54,.42]},{x0:-7,x1:7,z0:8,z1:23,step:1,color:[.43,.46,.43]},...SURFACE_PATCHES.map(p=>({...p,step:.5}))];
function patchSample(x,z,zone){const h=zone.step,fx=(x-zone.x0)/h,fz=(z-zone.z0)/h,ix=Math.floor(fx),iz=Math.floor(fz),u=fx-ix,w=fz-iz,px=zone.x0+ix*h,pz=zone.z0+iz*h,a=obstacles(px,pz),b=obstacles(px+h,pz),c=obstacles(px,pz+h),d=obstacles(px+h,pz+h);return u+w<=1?a+(b-a)*u+(c-a)*w:d+(c-d)*(1-u)+(b-d)*(1-w);}
function height(x,z){const zone=zones.find(q=>x>=q.x0&&x<=q.x1&&z>=q.z0&&z<=q.z1);let base=baseSample(x,z);for(const patch of SURFACE_PATCHES){const distance=Math.min(x-patch.x0,patch.x1-x,z-patch.z0,patch.z1-z),blend=smooth((distance+6)/6),level=baseSample((patch.x0+patch.x1)/2,(patch.z0+patch.z1)/2);base+=(level-base)*blend;}return base+(zone?patchSample(x,z,zone):0);}
function groundNormal(x,z){return norm([height(x-.04,z)-height(x+.04,z),.08,height(x,z-.04)-height(x,z+.04)]);}
function grip(x,z){return x>-7&&x<7&&z>8&&z<23?CAR_CONFIG.tyreGrip.pavement:Math.abs(x)<3?CAR_CONFIG.tyreGrip.road:CAR_CONFIG.tyreGrip.grass;}
function terrainMesh(x0,x1,z0,z1,step,skip=false,offset=.03){const v=[],n=[];for(let z=z0;z<z1-.001;z+=step)for(let x=x0;x<x1-.001;x+=step){if(skip&&zones.some(q=>x>=q.x0&&x<q.x1&&z>=q.z0&&z<q.z1))continue;for(const [dx,dz] of [[0,0],[step,0],[0,step],[step,0],[step,step],[0,step]]){v.push(x+dx,height(x+dx,z+dz)+offset,z+dz);n.push(...groundNormal(x+dx,z+dz));}}return mesh(v,n);}const terrain=terrainMesh(-80,80,-80,80,1,true);const testMeshes=zones.map(q=>({shape:terrainMesh(q.x0,q.x1,q.z0,q.z1,q.step,false,q.type==='WATER'?q.waterDepth:.03),color:q.color}));
function roadMesh(){const v=[],n=[];for(let z=-74;z<74;z+=2)for(const [x,dz] of [[-3,0],[3,0],[-3,2],[3,0],[3,2],[-3,2]]){v.push(x,height(x,z+dz)+.025,z+dz);n.push(...groundNormal(x,z+dz));}return mesh(v,n);}const road=roadMesh();
const objects=[];function box(x,y,z,sx,sy,sz,color,a=0){objects.push({m:matrix(x,y+height(x,z),z,sx,sy,sz,a),color});}let seed=73;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}for(let i=0;i<65;i++){const x=(rand()-.5)*140,z=(rand()-.5)*140,h=3+rand()*3;if(Math.abs(x)<8||Math.hypot(x,z)<12||zones.some(q=>x>q.x0-2&&x<q.x1+2&&z>q.z0-2&&z<q.z1+2))continue;box(x,h/2,z,.3,h,.3,[.36,.30,.23]);box(x,h,z,2.7,h*.6,2.7,[.25,.39,.28],rand()*3);box(x,h*1.3,z,1.8,h*.4,1.8,[.30,.45,.31],rand()*3);}for(let i=0;i<14;i++){const x=(rand()-.5)*130,z=(rand()-.5)*130;if(Math.abs(x)<9||zones.some(q=>x>q.x0-2&&x<q.x1+2&&z>q.z0-2&&z<q.z1+2))continue;box(x,.4,z,1+rand(),.8,1+rand(),[.51,.53,.46],rand()*3);}for(let i=-70;i<=70;i+=10){for(const x of [-74,74])box(x,.65,i,.2,1.3,.2,[.77,.75,.62]);for(const z of [-74,74])box(i,.65,z,.2,1.3,.2,[.77,.75,.62]);}box(7,.5,-10,1,1,1,[.67,.48,.3]);box(8.3,.4,-10,.8,.8,.8,[.67,.48,.3]);
const physics=new OffroadVehicle({height,normal:groundNormal,grip,surface:sampleSurface}),sound=new EngineAudio(document.querySelector('#sound'));
const car={x:0,z:4,a:Math.PI,v:0,steer:0,y:0},keys=new Set(),joy={x:0,y:0,id:null},look={x:0,y:0,id:null},orbit={yaw:0,elevation:.40,distance:8.4,idle:0},pedals={gas:false,brake:false};
function bindStick(selector,knobSelector,state,steeringOnly=false){const pad=document.querySelector(selector),knob=document.querySelector(knobSelector);function move(e){const r=pad.getBoundingClientRect(),radius=r.width*.35;let x=e.clientX-r.left-r.width/2,y=steeringOnly?0:e.clientY-r.top-r.height/2;const d=Math.hypot(x,y);if(d>radius){x*=radius/d;y*=radius/d;}state.x=x/radius;state.y=-y/radius;knob.style.transform=`translate(${x}px,${y}px)`;e.preventDefault();}function reset(){state.id=null;state.x=state.y=0;knob.style.transform='';}pad.addEventListener('pointerdown',e=>{if(state.id!==null)return;state.id=e.pointerId;pad.setPointerCapture(e.pointerId);move(e);});pad.addEventListener('pointermove',e=>{if(state.id===e.pointerId)move(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(event,e=>{if(e.pointerId===state.id)reset();});return reset;}
const release=bindStick('#stick','#knob',joy,true),lookRelease=()=>{look.id=null;look.x=look.y=0;};
const pedalResets=[];for(const [id,key] of [['#gas','gas'],['#brake','brake']]){const button=document.querySelector(id);let pointer=null;pedalResets.push(()=>{pointer=null;pedals[key]=false;button.classList.remove('active');});button.addEventListener('pointerdown',e=>{if(pointer!==null)return;pointer=e.pointerId;pedals[key]=true;button.setPointerCapture(pointer);button.classList.add('active');e.preventDefault();});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,e=>{if(e.pointerId===pointer){pointer=null;pedals[key]=false;button.classList.remove('active');}});}
// Invisible floating camera control, independent from steering and pedals.
let cameraTouch=null;function releaseFloating(){if(!cameraTouch)return;cameraTouch=null;lookRelease();}canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&e.clientX>=innerWidth/2&&look.id===null){look.id=e.pointerId;cameraTouch={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);e.preventDefault();}});canvas.addEventListener('pointermove',e=>{if(cameraTouch?.id===e.pointerId){let x=e.clientX-cameraTouch.x,y=e.clientY-cameraTouch.y,d=Math.hypot(x,y);if(d>40){x*=40/d;y*=40/d;}look.x=x/40;look.y=-y/40;e.preventDefault();}});for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{if(cameraTouch?.id===e.pointerId)releaseFloating();});
let drag=null;canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.clientX>=innerWidth/2){drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(drag&&drag.id===e.pointerId){orbit.yaw+=(e.clientX-drag.x)*.008;orbit.elevation=Math.max(.12,Math.min(1.12,orbit.elevation+(drag.y-e.clientY)*.006));orbit.idle=0;drag.x=e.clientX;drag.y=e.clientY;}});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(drag?.id===e.pointerId)drag=null;});
let focus=[0,1,4];function orbitTarget(dt){const active=look.id!==null||drag!==null;if(active)orbit.idle=0;else orbit.idle+=dt;orbit.yaw+=(Math.abs(look.x)>.08?look.x:0)*1.9*dt;orbit.yaw=Math.atan2(Math.sin(orbit.yaw),Math.cos(orbit.yaw));orbit.elevation=Math.max(.12,Math.min(1.12,orbit.elevation+(Math.abs(look.y)>.08?look.y:0)*1.05*dt));if(orbit.idle>1.6){const blend=1-Math.exp(-1.6*dt);orbit.yaw*=1-blend;orbit.elevation+=(.40-orbit.elevation)*blend;}focus=focus.map((v,i)=>v+([car.x,car.y+1.05,car.z][i]-v)*(1-Math.exp(-(i===1?3:8)*dt)));const angle=car.a+orbit.yaw,r=orbit.distance*Math.cos(orbit.elevation),x=focus[0]-Math.sin(angle)*r,z=focus[2]-Math.cos(angle)*r;return[x,Math.max(focus[1]+orbit.distance*Math.sin(orbit.elevation),height(x,z)+.9),z];}
const allowed=['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'];window.addEventListener('keydown',e=>{if(allowed.includes(e.code)){keys.add(e.code);e.preventDefault();}});window.addEventListener('keyup',e=>keys.delete(e.code));function clear(){keys.clear();releaseFloating();release();lookRelease();drag=null;handHeld=false;pedalResets.forEach(reset=>reset());for(const id of ['#gas','#brake'])document.querySelector(id).classList.remove('active');}window.addEventListener('blur',clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();});
let handHeld=false,hudTime=0;function step(dt){const drive=+(pedals.gas||keys.has('KeyW')||keys.has('ArrowUp'))-+(pedals.brake||keys.has('KeyS')||keys.has('ArrowDown'));const steer=Math.abs(joy.x)>.08?joy.x:+(keys.has('KeyD')||keys.has('ArrowRight'))-+(keys.has('KeyA')||keys.has('ArrowLeft'));physics.advance(dt,{drive,steer,handbrake:handHeld||keys.has('Space')});const origin=physics.matrix();car.x=origin[12];car.y=origin[13];car.z=origin[14];const front=rotate(physics.q,[0,0,1]);car.a=Math.atan2(front[0],front[2]);car.steer=physics.steer;car.v=physics.state.vehicleSpeed/3.6;sound.update(physics.state);hudTime+=dt;if(hudTime>=.1){updateHUD();hudTime=0;}}
function rotateX(a){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([1,0,0,0,0,c,s,0,0,-s,c,0,0,0,0,1]);}function rotateZ(a){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,s,0,0,-s,c,0,0,0,0,1,0,0,0,0,1]);}
// Reference-built low-poly Niva. Coordinates in metres, nose at +Z.
function polygonMesh(points){const vv=[],nn=[];for(let i=1;i<points.length-1;i++){const a=points[0],b=points[i],c=points[i+1],normal=norm(cross(b.map((v,j)=>v-a[j]),c.map((v,j)=>v-a[j])));for(const p of [a,b,c]){vv.push(...p);nn.push(...normal);}}return mesh(vv,nn);}
function extrude(profile,width){function half(p){return width/2-(width>1.65?Math.max(0,p[0]-1.60)*.22+Math.max(0,-p[0]-1.66)*.20:0);}const vv=[],nn=[];function tri(a,b,c){const normal=norm(cross(b.map((v,j)=>v-a[j]),c.map((v,j)=>v-a[j])));for(const p of [a,b,c]){vv.push(...p);nn.push(...normal);}}
// Ear clipping preserves the concave openings over all four tyres.
let ids=profile.map((_,i)=>i);const area=profile.reduce((s,p,i)=>{const q=profile[(i+1)%profile.length];return s+p[0]*q[1]-q[0]*p[1];},0),sign=Math.sign(area);const cross2=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);const inside=(p,a,b,c)=>sign*cross2(a,b,p)>=-1e-8&&sign*cross2(b,c,p)>=-1e-8&&sign*cross2(c,a,p)>=-1e-8;let guard=0;while(ids.length>2&&guard++<500){let found=false;for(let j=0;j<ids.length;j++){const ia=ids[(j+ids.length-1)%ids.length],ib=ids[j],ic=ids[(j+1)%ids.length],a=profile[ia],b=profile[ib],c=profile[ic];if(sign*cross2(a,b,c)<=1e-8)continue;if(ids.some(k=>k!==ia&&k!==ib&&k!==ic&&inside(profile[k],a,b,c)))continue;for(const side of [-1,1])tri([side*half(a),a[1],a[0]],[side*half(b),b[1],b[0]],[side*half(c),c[1],c[0]]);ids.splice(j,1);found=true;break;}if(!found)throw Error('Car profile triangulation failed');}
for(let i=0;i<profile.length;i++){const a=profile[i],b=profile[(i+1)%profile.length],p=[-half(a),a[1],a[0]],q=[half(a),a[1],a[0]],r=[half(b),b[1],b[0]],t=[-half(b),b[1],b[0]];tri(p,q,r);tri(p,r,t);}return mesh(vv,nn);}
const lower=[[-1.82,.53]];for(const centre of [-1.1,1.1]){const radius=.51,start=Math.asin((.53-.44)/radius);for(let i=0;i<=14;i++){const a=Math.PI-start-(Math.PI-2*start)*i/14;lower.push([centre+radius*Math.cos(a),.44+radius*Math.sin(a)]);}}lower.push([1.82,.53],[1.84,1.06],[1.77,1.145],[.75,1.185],[.55,1.17],[-1.81,1.09]);
const shell=extrude(lower,1.68),cabin=extrude([[-1.81,1.085],[-1.43,1.70],[.17,1.70],[.75,1.18]],1.58);
function sheet(xs,zs,top,side,warp=(x,z)=>z){const pt=(x,z,y)=>[x,y,warp(x,z)];const v=[],n=[];function triangle(a,b,c){const normal=norm(cross(b.map((v,i)=>v-a[i]),c.map((v,i)=>v-a[i])));for(const p of [a,b,c]){v.push(...p);n.push(...normal);}}
for(let j=0;j<zs.length-1;j++)for(let i=0;i<xs.length-1;i++){const a=pt(xs[i],zs[j],top(xs[i],zs[j])),b=pt(xs[i+1],zs[j],top(xs[i+1],zs[j])),c=pt(xs[i+1],zs[j+1],top(xs[i+1],zs[j+1])),d=pt(xs[i],zs[j+1],top(xs[i],zs[j+1]));triangle(a,d,b);triangle(b,d,c);}
for(const x of [xs[0],xs.at(-1)])for(let j=0;j<zs.length-1;j++){const a=pt(x,zs[j],top(x,zs[j])),b=pt(x,zs[j+1],top(x,zs[j+1])),c=pt(x,zs[j+1],side(x,zs[j+1])),d=pt(x,zs[j],side(x,zs[j]));triangle(a,b,c);triangle(a,c,d);}
for(const z of [zs[0],zs.at(-1)])for(let i=0;i<xs.length-1;i++){const a=pt(xs[i],z,top(xs[i],z)),b=pt(xs[i+1],z,top(xs[i+1],z)),c=pt(xs[i+1],z,side(xs[i+1],z)),d=pt(xs[i],z,side(xs[i],z));triangle(a,b,c);triangle(a,c,d);}return mesh(v,n);}
function roofTop(x,z){const across=Math.max(0,1-(x/.815)**2),along=Math.max(0,1-((z+.59)/.89)**4);return 1.704+.09*across+.015*along;}
const roof=sheet([-.815,-.74,-.50,0,.50,.74,.815],[-1.46,-1.37,-1.05,-.55,-.05,.14,.24],roofTop,()=>1.69,(x,z)=>z-(z+.61)*.10*(Math.abs(x)/.815)**6);
function bonnetTop(x,z){return 1.185-(z-.72)*.045+.034*Math.max(0,1-(x/.79)**2);}
const bonnet=sheet([-.79,-.72,-.42,0,.42,.72,.79],[.72,.81,1.22,1.65,1.77,1.83],bonnetTop,(x,z)=>z>1.75?1.065:1.15);
const glazing=[];function panel(points,color){glazing.push({shape:polygonMesh(points),color});}
const green=[.20,.32,.30],dark=[.075,.095,.085],rubber=[.105,.115,.105],glass=[.24,.36,.38],chrome=[.65,.68,.65];
for(const side of [-1,1]){const x=side*.795;
panel([[x,1.16,-1.63],[x,1.47,-1.52],[x,1.65,-1.33],[x,1.65,-.48],[x,1.16,-.48]],dark);
panel([[x+side*.002,1.20,-1.58],[x+side*.002,1.47,-1.47],[x+side*.002,1.60,-1.30],[x+side*.002,1.60,-.53],[x+side*.002,1.20,-.53]],glass);
panel([[x,1.225,-.40],[x,1.65,-.40],[x,1.65,.12],[x,1.225,.57]],dark);
panel([[x+side*.002,1.26,-.35],[x+side*.002,1.60,-.35],[x+side*.002,1.60,.105],[x+side*.002,1.26,.50]],glass);
// Small triangular vent window, separated by a thin frame.
panel([[x+side*.004,1.24,.32],[x+side*.004,1.44,.32],[x+side*.004,1.24,.55]],dark);
panel([[x+side*.006,1.265,.355],[x+side*.006,1.405,.355],[x+side*.006,1.265,.495]],glass);
}
function frontPlane(y,offset=0){return .75-(y-1.18)*.58/.52+offset;}
const windOutline=[[-.71,1.235],[.71,1.235],[.71,1.615],[.665,1.666],[-.665,1.666],[-.71,1.615]];
const windGlass=[[-.678,1.263],[.678,1.263],[.678,1.604],[.645,1.639],[-.645,1.639],[-.678,1.604]];
panel(windOutline.map(([x,y])=>[x,y,frontPlane(y,.01)]),dark);
panel(windGlass.map(([x,y])=>[x,y,frontPlane(y,.015)]),glass);
// Rear glass and trim share one plane, offset slightly from the tailgate.
// The previous non-planar fan intersected the crease in the rear body surface.
function rearPlane(y,offset=0){return -1.81+(y-1.085)*.38/.615-offset;}
const rearOutline=[[-.70,1.20],[.70,1.20],[.70,1.57],[.63,1.65],[-.63,1.65],[-.70,1.57]];
const rearGlass=[[-.665,1.235],[.665,1.235],[.665,1.555],[.614,1.615],[-.614,1.615],[-.665,1.555]];
panel(rearOutline.map(([x,y])=>[x,y,rearPlane(y,.009)]),dark);
panel(rearGlass.map(([x,y])=>[x,y,rearPlane(y,.014)]),glass);
const archDetails=[];for(const side of [-1,1])for(const centre of [-1.1,1.1])for(let i=0;i<18;i++){const a=.18+i*(Math.PI-.36)/18,b=.18+(i+1)*(Math.PI-.36)/18;const points=[];for(const [angle,radius] of [[a,.512],[b,.512],[b,.555],[a,.555]])points.push([side*.846,.44+Math.sin(angle)*radius,centre+Math.cos(angle)*radius]);archDetails.push(polygonMesh(points));}
function linePart(a,b,width,color){const direction=norm(b.map((v,i)=>v-a[i])),right=norm(cross(direction,Math.abs(direction[1])>.9?[1,0,0]:[0,1,0])),up=cross(direction,right),length=Math.hypot(...b.map((v,i)=>v-a[i])),mid=a.map((v,i)=>(v+b[i])/2);const m=new Float32Array([...right.map(v=>v*width),0,...up.map(v=>v*width),0,...direction.map(v=>v*length),0,...mid,1]);draw(cube,mul(body,m),color);}
let body;function part(x,y,z,sx,sy,sz,col){draw(cube,mul(body,matrix(x,y,z,sx,sy,sz)),col);}const facing=new Float32Array([1,0,0,0,0,0,1,0,0,-1,0,0,0,0,0,1]);function roundPart(x,y,z,r,depth,col){draw(cylinder,mul(mul(body,matrix(x,y,z,1,1,1)),mul(facing,matrix(0,0,0,r,depth,r))),col);}
function vehicle(){body=physics.matrix();draw(shell,body,green);draw(cabin,body,green);draw(roof,body,green);draw(bonnet,body,green);for(const panel of glazing)draw(panel.shape,body,panel.color);
part(0,.49,0,1.32,.12,2.6,dark);
// Thin arch mouldings, roof gutters, bonnet stampings and wipers.
for(const arch of archDetails)draw(arch,body,[.23,.32,.28]);
for(const side of [-1,1]){linePart([side*.82,1.699,-1.35],[side*.82,1.699,.12],.018,chrome);linePart([side*.66,bonnetTop(side*.66,.81)+.004,.81],[side*.66,bonnetTop(side*.66,1.68)+.004,1.68],.012,[.29,.38,.33]);linePart([side*.44,1.276,frontPlane(1.276,.027)],[side*.16,1.301,frontPlane(1.301,.027)],.014,dark);linePart([side*.838,1.14,.74],[side*.838,1.12,1.72],.01,dark);part(side*.845,1.08,.96,.009,.055,.14,[.76,.47,.16]);}
// Tailgate perimeter, rear wiper, vents and small licence plates.
linePart([-.73,.71,-1.837],[.73,.71,-1.837],.013,dark);for(const side of [-1,1])linePart([side*.73,.72,-1.837],[side*.73,1.12,-1.837],.013,dark);linePart([.03,1.245,rearPlane(1.245,.025)],[.34,1.27,rearPlane(1.27,.025)],.016,dark);part(0,.648,1.989,.40,.083,.014,[.81,.81,.72]);
for(const side of [-1,1])for(let i=0;i<3;i++)part(side*.803,1.43+i*.039,-1.59,.014,.012,.09,dark);
// Door outlines and recognisable body crease under the glazing.
for(const side of [-1,1]){const x=side*.843;part(x,1.10,-.55,.009,.012,2.32,[.30,.38,.34]);part(x,.80,-.44,.009,.53,.012,dark);part(x,.72,.57,.009,.27,.012,dark);part(x,.548,.03,.009,.012,.9,dark);part(x,1.025,-.24,.025,.035,.15,chrome);part(side*.86,1.23,.52,.11,.028,.035,dark);part(side*.925,1.275,.52,.12,.12,.07,dark);}
// Round lamps, rectangular indicators, narrow grille and plain bumpers.
for(const x of [-.645,.645]){roundPart(x,.93,1.852,.285,.018,dark);roundPart(x,.93,1.873,.237,.023,[.88,.87,.70]);roundPart(x-.035,.970,1.889,.065,.01,[.97,.97,.88]);part(x,1.112,1.842,.25,.067,.025,dark);part(x,1.115,1.860,.20,.043,.018,[.90,.67,.30]);part(x,.85,-1.833,.17,.27,.025,dark);part(x,.91,-1.849,.135,.13,.018,[.69,.19,.12]);part(x,.807,-1.849,.135,.055,.018,[.93,.61,.25]);}
part(0,.86,1.855,.89,.25,.019,dark);for(let i=0;i<4;i++)part(0,.77+i*.057,1.873,.85,.012,.016,chrome);for(let i=-3;i<=3;i++)part(i*.105,.855,1.877,.014,.22,.012,[.32,.37,.34]);part(0,.87,1.896,.055,.075,.01,chrome);
for(const z of [-1.90,1.91]){part(0,.64,z,1.83,.10,.13,chrome);for(const x of [-.61,.61])part(x,.64,z+(z>0?.077:-.077),.11,.16,.025,dark);}
part(0,.77,-1.847,.43,.13,.02,dark);part(0,.773,-1.863,.36,.083,.012,[.83,.83,.75]);part(0,1.04,-1.831,.14,.03,.025,chrome);
// Steel rims with small circular holes; no spinning rectangles outside tyres.
// Rear beam follows both independent wheel contacts.
const left=physics.wheels[2].position,right=physics.wheels[3].position,beam=norm(right.map((v,i)=>v-left[i])),beamUp=norm(cross([0,0,1],beam)),beamSide=cross(beam,beamUp),mid=left.map((v,i)=>(v+right[i])/2);draw(cube,new Float32Array([...beam.map(v=>v*1.70),0,...beamUp.map(v=>v*.12),0,...beamSide.map(v=>v*.12),0,...mid,1]),dark);
for(const w of physics.wheels){const up=rotate(physics.q,[0,1,0]),localForward=rotate(physics.q,[Math.sin(w.steer),0,Math.cos(w.steer)]),axis=w.front?norm(cross(up,localForward)):beam,wheelUp=norm(cross(localForward,axis));let m=new Float32Array([...axis,0,...wheelUp,0,...localForward,0,...w.position.map((v,i)=>v-(i===1?w.visualSink||0:0)),1]);m=mul(m,rotateX(w.angle));const axle=(diameter,width)=>new Float32Array([0,diameter,0,0,-width,0,0,0,0,0,diameter,0,0,0,0,1]);draw(cylinder,mul(m,axle(CAR_CONFIG.wheelRadius*2,.25)),rubber);draw(cylinder,mul(m,axle(.53,.259)),chrome);draw(cylinder,mul(m,axle(.17,.275)),[.40,.44,.41]);for(let i=0;i<6;i++){const a=i*Math.PI/3,local=matrix(Math.sign(w.x)*.134,Math.cos(a)*.18,Math.sin(a)*.18,1,1,1);draw(cylinder,mul(m,mul(local,axle(.075,.008))),dark);}}}
const hud={gear:document.querySelector('#gear'),rpm:document.querySelector('#rpm'),range:document.querySelector('#range'),center:document.querySelector('#center-lock'),rear:document.querySelector('#rear-lock'),wheels:document.querySelector('#wheel-status')};
function updateHUD(){const s=physics.state;hud.gear.textContent=(s.currentGear<0?'R':s.currentGear)+' | '+s.transferRange+' | 4WD'+(s.centerLocked?' · C':'')+(s.rearLocked?' · R':'')+((s.pendingRange||s.pendingCenter||s.pendingRear)?' · WAIT':'');hud.rpm.textContent=Math.round(s.currentRPM)+' RPM';hud.range.textContent=s.pendingRange?'H/L · WAIT':'H/L · '+s.transferRange;hud.center.textContent=s.pendingCenter?'C LOCK · WAIT':'C LOCK '+(s.centerLocked?'ON':'OFF');hud.rear.textContent=s.pendingRear?'R LOCK · WAIT':'R LOCK '+(s.rearLocked?'ON':'OFF');hud.center.classList.toggle('active',s.centerLocked);hud.rear.classList.toggle('active',s.rearLocked);hud.range.classList.toggle('active',s.transferRange==='L');hud.center.setAttribute('aria-pressed',String(s.centerLocked));hud.rear.setAttribute('aria-pressed',String(s.rearLocked));document.querySelector('#surface').textContent=[...new Set(physics.wheels.filter(w=>w.contact).map(w=>w.surfaceType||'DIRT'))].join(' / ');if(!transmissionPanel.hidden)hud.wheels.innerHTML=physics.wheels.map(w=>`<i class="${w.contact&&w.load>100?'contact':'air'}" title="${w.id}: ${Math.round(w.load)} N">${w.id} ${w.surfaceType||'DIRT'}${Math.abs(w.slipRatio)>.22&&w.contact?' ↻':''}</i>`).join('');}
hud.range.addEventListener('click',()=>physics.requestRange());hud.center.addEventListener('click',()=>physics.requestCenter());hud.rear.addEventListener('click',()=>physics.requestRear());const hand=document.querySelector('#handbrake');hand.addEventListener('pointerdown',e=>{handHeld=true;hand.setPointerCapture(e.pointerId);hand.classList.add('active');e.preventDefault();});for(const type of ['pointerup','pointercancel','lostpointercapture'])hand.addEventListener(type,()=>{handHeld=false;hand.classList.remove('active');});document.querySelector('#reset').addEventListener('click',()=>{physics.reset();clear();});
const transmissionPanel=document.querySelector('#transmission-panel'),toggle=document.querySelector('#transmission');transmissionPanel.hidden=true;toggle.addEventListener('click',()=>{transmissionPanel.hidden=!transmissionPanel.hidden;toggle.setAttribute('aria-expanded',String(!transmissionPanel.hidden));});
const signs=[...SURFACE_PATCHES.map(p=>({x:(p.x0+p.x1)/2,z:p.z1,text:p.label})),{x:10,z:-4,text:'01 · ДИАГОНАЛЬ'},{x:-12,z:-3,text:'02 · ПОДЪЁМ H / L'},{x:0,z:10,text:'03 · ПОВОРОТ'}];for(const sign of signs){sign.el=document.createElement('div');sign.el.className='world-sign';sign.el.textContent=sign.text;document.body.appendChild(sign.el);}
function updateSigns(){for(const sign of signs){const p=[sign.x,height(sign.x,sign.z)+1.4,sign.z,1],q=[0,1,2,3].map(r=>p.reduce((sum,v,i)=>sum+pv[i*4+r]*v,0));if(q[3]<=0||Math.abs(q[0]/q[3])>1||Math.abs(q[1]/q[3])>1||Math.hypot(car.x-sign.x,car.z-sign.z)>35){sign.el.hidden=true;continue;}sign.el.hidden=false;sign.el.style.transform=`translate(${(q[0]/q[3]*.5+.5)*innerWidth}px,${(-q[1]/q[3]*.5+.5)*innerHeight}px) translate(-50%,-50%)`;}}

let portraitPaused=false;
function updateOrientation(){const portrait=!!window.matchMedia?.('(orientation: portrait) and (pointer: coarse)').matches;if(portrait!==portraitPaused){clear();portraitPaused=portrait;}document.querySelector('#rotate-hint').setAttribute('aria-hidden',String(!portrait));}
window.addEventListener('resize',updateOrientation);window.addEventListener('orientationchange',updateOrientation);updateOrientation();
document.querySelector('#fullscreen').addEventListener('click',async()=>{try{if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();}catch{}try{if(window.screen?.orientation?.lock)await window.screen.orientation.lock('landscape');}catch{}});
let camera=[0,5.2,12.7],last=0;gl.enable(gl.DEPTH_TEST);gl.clearColor(.73,.79,.74,1);const speed=document.querySelector('#speed'),gear=document.querySelector('#gear');function frame(t){const dt=Math.min((t-last)/1000||.016,.05);last=t;if(!portraitPaused)step(dt);const target=orbitTarget(dt);camera=camera.map((v,i)=>v+(target[i]-v)*(1-Math.exp(-6*dt)));camera[1]=Math.max(camera[1],height(camera[0],camera[2])+.7);const dpr=Math.min(devicePixelRatio||1,1.5),w=Math.round(innerWidth*dpr),h=Math.round(innerHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h);}const f=1/Math.tan(Math.PI/6),near=.1,far=180;pv=mul(new Float32Array([f/(w/h),0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]),view(camera,focus));gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);draw(terrain,matrix(0,0,0,1,1,1),[.46,.54,.39]);draw(road,matrix(0,0,0,1,1,1),[.65,.63,.50]);for(const t of testMeshes)draw(t.shape,matrix(0,0,0,1,1,1),t.color);for(const o of objects)draw(cube,o.m,o.color);vehicle();updateSigns();speed.textContent=Math.round(Math.abs(car.v)*3.6);requestAnimationFrame(frame);}canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();clear();document.querySelector('#error').hidden=false;document.querySelector('#error').textContent='3D-контекст потерян. Перезагрузи страницу.';});requestAnimationFrame(frame);
export {physics,height,groundNormal,grip,sampleSurface,orbit,pedals};
