import {SURFACE_SETTINGS} from './surfaces.js?v=0062';
// Four vertical heightfield casts + one free rigid chassis. SI units throughout.
export const CAR_CONFIG={mass:1280,centerOfMass:[0,.82,0],inertia:[1580,1880,640],gravity:9.81,wheelRadius:.44,wheelInertia:2.4,mountHeight:.94,track:1.72,wheelbase:2.24,springRate:{front:27000,rear:25000},damping:{front:3200,rear:2900},suspensionTravel:{front:{compression:.145,droop:.115,rest:.62},rear:{compression:.165,droop:.145,rest:.64}},antiRoll:{front:3700,rear:650},rearAxleCoupling:1000,bumpStop:85000,maxSpringForce:21000,gearRatios:[3.67,2.10,1.36,1,.82],reverseRatio:3.53,finalDrive:3.9,highRangeRatio:1.2,lowRangeRatio:2.1,engineTorqueCurve:[[850,78],[1400,112],[2200,135],[3200,143],[4200,130],[5200,105],[6000,65],[6200,0]],idleRPM:850,redlineRPM:6200,engineBraking:25,engineResponse:7,maxReverseSpeed:5.5,drivetrainEfficiency:.86,shiftDuration:.22,shiftCooldown:1.0,upshiftRPM:[3150,5100],downshiftRPM:1450,tyreGrip:{grass:.76,road:.90,pavement:1.12},tyreLongStiffness:7.5,tyreSideStiffness:4.0,tyrePostPeak:.24,rollingResistance:.025,aeroDrag:.68,steeringAngle:.53,steeringResponse:6,throttleResponse:4.5,brakeTorque:1750,handbrakeTorque:2700,differentialSettings:{parasiticTorque:10,centerCoupling:950,rearCoupling:850,centerTurnResistance:110,rearTurnResistance:2200,centerFrontGripFactor:.93,rearFrontGripFactor:.58,rearEnableSpeed:5,rearEnableDifference:9,centerEnableDifference:18,rangeEnableSpeed:1.39,rangeEnableThrottle:.1},bodyContact:{spring:75000,damping:5000,friction:.65},fixedStep:1/180,mapLimit:71};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),scale=(a,s)=>a.map(v=>v*s),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],unit=a=>scale(a,1/(Math.hypot(...a)||1));
export function rotate(q,v){const t=scale(cross(q.slice(0,3),v),2);return add(v,add(scale(t,q[3]),cross(q.slice(0,3),t)));}
function inverse(q,v){return rotate([-q[0],-q[1],-q[2],q[3]],v);}function torqueCurve(c,rpm){const a=c.engineTorqueCurve;for(let i=1;i<a.length;i++)if(rpm<a[i][0]){const t=clamp((rpm-a[i-1][0])/(a[i][0]-a[i-1][0]),0,1);return a[i-1][1]*(1-t)+a[i][1]*t;}return 0;}
export function axleCapacity(wheels,locked,c=CAR_CONFIG){const cap=wheels.map(w=>w.contact?w.load*w.mu*c.wheelRadius*(w.surface?.slipResistance||1):0);return locked?cap[0]+cap[1]:2*Math.min(...cap)+c.differentialSettings.parasiticTorque*2;}
export function distributeTorque(total,wheels,centerLocked,rearLocked,c=CAR_CONFIG){const front=axleCapacity(wheels.slice(0,2),false,c),rear=axleCapacity(wheels.slice(2),rearLocked,c),amount=Math.abs(total),sign=Math.sign(total);let f,r;if(centerLocked){const sum=front+rear||1;f=Math.min(front,amount*front/sum);r=Math.min(rear,amount*rear/sum);}else f=r=Math.min(amount/2,front,rear);const capacities=wheels.slice(2).map(w=>w.contact?w.load*w.mu*c.wheelRadius*(w.surface?.slipResistance||1):c.differentialSettings.parasiticTorque),sum=capacities[0]+capacities[1]||1;return[f*.5*sign,f*.5*sign,r*(rearLocked?capacities[0]/sum:.5)*sign,r*(rearLocked?capacities[1]/sum:.5)*sign];}
export class OffroadVehicle{
 constructor(terrain,c=CAR_CONFIG){this.c=c;this.terrain=terrain;this.state={currentGear:1,currentRPM:c.idleRPM,transferRange:'H',centerLocked:false,rearLocked:false,pendingRange:null,pendingCenter:null,pendingRear:null,throttle:0,brake:0,vehicleSpeed:0,frontAxleRPM:0,rearAxleRPM:0,shiftRemaining:0,load:0,handbrake:false};this.wheels=[[-c.track/2,c.wheelbase/2],[c.track/2,c.wheelbase/2],[-c.track/2,-c.wheelbase/2],[c.track/2,-c.wheelbase/2]].map(([x,z],i)=>({id:['FL','FR','RL','RR'][i],x,z,front:i<2,omega:0,angle:0,load:0,contact:false,length:.6,compression:0,compressionSpeed:0,slipRatio:0,slipAngle:0,mu:.8,position:[0,0,0],normal:[0,1,0],steer:0,longForce:0,sideForce:0}));this.reset();}
 reset(x=0,z=4,yaw=Math.PI){this.p=[x,this.terrain.height(x,z)+this.c.centerOfMass[1]+.15,z];this.v=[0,0,0];this.omega=[0,0,0];this.q=[0,Math.sin(yaw/2),0,Math.cos(yaw/2)];this.steer=0;this.cooldown=0;this.accumulator=0;this.reverseHold=0;this.state.currentGear=1;this.state.currentRPM=this.c.idleRPM;this.state.shiftRemaining=0;for(const w of this.wheels){w.omega=w.angle=0;w.load=0;w.surface=null;}this.state.throttle=0; }
 point(local){return add(this.p,rotate(this.q,sub(local,this.c.centerOfMass)));}velocityAt(p){return add(this.v,cross(this.omega,sub(p,this.p)));}
 requestRange(){this.state.pendingRange=(this.state.pendingRange||this.state.transferRange)==='H'?'L':'H';if(this.state.pendingRange===this.state.transferRange)this.state.pendingRange=null;}
 requestCenter(){const s=this.state,target=!(s.pendingCenter??s.centerLocked);if(!target){s.centerLocked=false;s.pendingCenter=null;}else s.pendingCenter=true;}
 requestRear(){const s=this.state,target=!(s.pendingRear??s.rearLocked);if(!target){s.rearLocked=false;s.pendingRear=null;}else s.pendingRear=true;}
 advance(dt,input){this.accumulator+=Math.min(dt,.075);let n=0;while(this.accumulator>=this.c.fixedStep&&n++<14){this.tick(this.c.fixedStep,input);this.accumulator-=this.c.fixedStep;}}
 tick(dt,input){const c=this.c,s=this.state,forward=rotate(this.q,[0,0,1]);const speed=dot(this.v,forward),command=clamp(input.drive||0,-1,1),desired=command<-.08?-1:command>.08?1:0,direction=s.currentGear===-1?-1:1;this.steer+=(clamp(input.steer||0,-1,1)-this.steer)*(1-Math.exp(-c.steeringResponse*dt));s.handbrake=!!input.handbrake;s.brake=desired&&desired!==direction?Math.abs(command):0;s.throttle+=( (desired===direction?Math.abs(command):0)-s.throttle)*(1-Math.exp(-c.throttleResponse*dt));if(s.brake)s.throttle=0;s.throttleInput=desired===direction?Math.abs(command):0;s.steeringInput=clamp(input.steer||0,-1,1);
 if(desired&&desired!==direction&&Math.hypot(this.v[0],this.v[2])<.28){this.reverseHold+=dt;if(this.reverseHold>.16){s.currentGear=desired<0?-1:1;s.shiftRemaining=c.shiftDuration;s.throttle=0;this.reverseHold=0;}}else this.reverseHold=0;
 s.vehicleSpeed=Math.hypot(this.v[0],this.v[2])*3.6;const settings=c.differentialSettings;if(s.pendingRange&&s.vehicleSpeed/3.6<settings.rangeEnableSpeed&&Math.abs(command)<settings.rangeEnableThrottle){s.transferRange=s.pendingRange;s.pendingRange=null;s.shiftRemaining=c.shiftDuration;this.cooldown=.6;}
 const frontOmega=(this.wheels[0].omega+this.wheels[1].omega)/2,rearOmega=(this.wheels[2].omega+this.wheels[3].omega)/2;
 if(s.pendingCenter&&Math.abs(frontOmega-rearOmega)<settings.centerEnableDifference&&s.throttle<.35){s.centerLocked=true;s.pendingCenter=null;}
 if(s.pendingRear&&s.vehicleSpeed/3.6<settings.rearEnableSpeed&&Math.abs(this.wheels[2].omega-this.wheels[3].omega)<settings.rearEnableDifference&&s.throttle<.35){s.rearLocked=true;s.pendingRear=null;}
 const ratio=(s.currentGear<0?c.reverseRatio:c.gearRatios[s.currentGear-1])*(s.transferRange==='L'?c.lowRangeRatio:c.highRangeRatio)*c.finalDrive;
 const shaft=Math.abs((frontOmega+rearOmega)/2),shaftRPM=shaft*ratio*60/(2*Math.PI),launch=1-clamp(shaftRPM/1500,0,1);const targetRPM=clamp(Math.max(c.idleRPM,shaftRPM,c.idleRPM+s.throttle*1700*launch),c.idleRPM,c.redlineRPM);s.currentRPM+=(targetRPM-s.currentRPM)*(1-Math.exp(-c.engineResponse*dt));s.shiftRemaining=Math.max(0,s.shiftRemaining-dt);this.cooldown=Math.max(0,this.cooldown-dt);
 const up=(c.upshiftRPM[0]+(c.upshiftRPM[1]-c.upshiftRPM[0])*s.throttle)*(s.transferRange==='L'?1.08:1),expectedDown=s.currentGear>1?s.currentRPM*c.gearRatios[s.currentGear-2]/c.gearRatios[s.currentGear-1]:0;
 if(s.currentGear>0&&!s.shiftRemaining&&!this.cooldown&&Math.abs(speed)>.5){if(s.currentRPM>up&&s.currentGear<5&&s.load<.94){s.currentGear++;s.shiftRemaining=c.shiftDuration;this.cooldown=c.shiftCooldown;}else if(s.currentRPM<c.downshiftRPM+(s.load>.75?350:0)&&s.currentGear>1&&expectedDown<up-500){s.currentGear--;s.shiftRemaining=c.shiftDuration;this.cooldown=c.shiftCooldown;}}
 let force=[0,-c.mass*c.gravity,0],moment=[0,0,0];const apply=(f,p)=>{force=add(force,f);moment=add(moment,cross(sub(p,this.p),f));};
 for(const w of this.wheels){const axle=w.front?'front':'rear',travel=c.suspensionTravel[axle],mount=this.point([w.x,c.mountHeight,w.z]),ground=this.terrain.height(mount[0],mount[2]),n=this.terrain.normal(mount[0],mount[2]),length=mount[1]-ground-c.wheelRadius,compression=travel.rest-length,mountV=this.velocityAt(mount),rate=-dot(mountV,n)/Math.max(.3,n[1]);w.distanceToSurface=mount[1]-ground;w.contact=length<=travel.rest+travel.droop&&rotate(this.q,[0,1,0])[1]>.08;w.length=clamp(length,travel.rest-travel.compression,travel.rest+travel.droop);w.compression=clamp(compression,-travel.droop,travel.compression);w.compressionSpeed=rate;w.normal=n;const target=this.terrain.surface?.(mount[0],mount[2]);if(target){w.surfaceType=target.surfaceType;w.mudDepth=target.mudDepth;w.waterDepth=target.waterDepth;if(!w.surface)w.surface={...target};const blend=1-Math.exp(-dt/SURFACE_SETTINGS.transitionTime);for(const key of ['longitudinalGrip','lateralGrip','rollingResistance','slipResistance','sinkAmount','effectMultiplier','vibrationMultiplier'])w.surface[key]+=(target[key]-w.surface[key])*blend;w.mu=w.surface.longitudinalGrip;}else w.mu=this.terrain.grip(mount[0],mount[2]);w.position=rotate(this.q,[0,1,0])[1]>.08?[mount[0],mount[1]-w.length,mount[2]]:add(mount,scale(rotate(this.q,[0,-1,0]),travel.rest+travel.droop));w.load=w.contact?clamp(c.springRate[axle]*compression+c.damping[axle]*rate+c.bumpStop*Math.max(0,compression-travel.compression),0,c.maxSpringForce):0;w.point=[mount[0],ground,mount[2]];}
 // Front anti-roll and a much softer rear bridge coupling, applied at contacts.
 for(const pair of [[0,1,c.antiRoll.front],[2,3,c.antiRoll.rear+c.rearAxleCoupling]]){const a=this.wheels[pair[0]],b=this.wheels[pair[1]],coupling=(a.compression-b.compression)*pair[2];if(a.contact)a.load=clamp(a.load+coupling,0,c.maxSpringForce);if(b.contact)b.load=clamp(b.load-coupling,0,c.maxSpringForce);}
 const cut=s.shiftRemaining?(.18+.82*(1-s.shiftRemaining/c.shiftDuration)**2):1;let engineTorque=torqueCurve(c,s.currentRPM)*s.throttle;if(s.currentGear<0)engineTorque*=clamp((c.maxReverseSpeed-Math.abs(speed))/1.4,0,1);if(s.currentRPM>c.redlineRPM-80)engineTorque=0;if(!s.throttle&&shaftRPM>c.idleRPM+100)engineTorque=-c.engineBraking*clamp((s.currentRPM-c.idleRPM)/1600,0,1);let driveTorque=engineTorque*ratio*c.drivetrainEfficiency*direction*cut;const torques=distributeTorque(driveTorque,this.wheels,s.centerLocked,s.rearLocked,c);s.load=clamp(Math.abs(driveTorque)/(this.wheels.reduce((sum,w)=>sum+w.load*w.mu*c.wheelRadius,0)+100),0,1);
 // Internal reaction torques conserve total torque while tying differential shafts.
 if(s.centerLocked){const reaction=clamp((frontOmega-rearOmega)*c.wheelInertia/(2*dt),-settings.centerCoupling,settings.centerCoupling);torques[0]-=reaction/2;torques[1]-=reaction/2;torques[2]+=reaction/2;torques[3]+=reaction/2;}
 if(s.rearLocked){const reaction=clamp((this.wheels[2].omega-this.wheels[3].omega)*c.wheelInertia/(2*dt),-settings.rearCoupling,settings.rearCoupling);torques[2]-=reaction;torques[3]+=reaction;}
 for(let i=0;i<4;i++){const w=this.wheels[i];w.steer=w.front?-this.steer*c.steeringAngle/(1+Math.abs(speed)*.035):0;const localForward=[Math.sin(w.steer),0,Math.cos(w.steer)],wf=rotate(this.q,localForward),tangent=unit(sub(wf,scale(w.normal,dot(wf,w.normal)))),side=unit(cross(w.normal,tangent)),pointV=this.velocityAt(w.point),vl=dot(pointV,tangent),vs=dot(pointV,side);w.slipRatio=(w.omega*c.wheelRadius-vl)/Math.max(1.5,Math.abs(vl));w.slipAngle=Math.atan2(vs,Math.max(.8,Math.abs(vl)));let torque=torques[i];const brake=s.brake*c.brakeTorque+(s.handbrake&&!w.front?c.handbrakeTorque:0);if(brake){const predicted=w.omega+torque/c.wheelInertia*dt;torque-=clamp(predicted*c.wheelInertia/dt,-brake,brake);}let fx=0,fy=0;if(w.contact&&w.load>0){const cap=w.load*w.mu*(1-(w.surfaceType==='MUD'?SURFACE_SETTINGS.mudPostPeak:c.tyrePostPeak)*clamp((Math.abs(w.slipRatio)-.18)/1.2,0,1)),k=w.load*c.tyreLongStiffness/Math.max(1.5,Math.abs(vl));fx=clamp(k*(w.omega*c.wheelRadius+torque/c.wheelInertia*dt*c.wheelRadius-vl)/(1+k*c.wheelRadius**2*dt/c.wheelInertia+k*dt/c.mass),-cap,cap);let lateral=w.load*c.tyreSideStiffness*(w.surface?w.surface.lateralGrip/w.mu:1);if(!w.front&&s.handbrake)lateral*=.28;if(w.front&&w.mu>1){if(s.rearLocked)lateral*=settings.rearFrontGripFactor;if(s.centerLocked)lateral*=settings.centerFrontGripFactor;}const sideCap=w.load*(w.surface?.lateralGrip||w.mu);fy=clamp(-w.slipAngle*lateral,-sideCap,sideCap);const ellipse=Math.hypot(fx/Math.max(1,cap),fy/Math.max(1,sideCap));if(ellipse>1){fx/=ellipse;fy/=ellipse;}apply(scale(w.normal,w.load),w.point);apply(add(scale(tangent,fx),scale(side,fy)),w.point);apply(scale(tangent,-Math.tanh(vl*2)*w.load*(w.surface?.rollingResistance??c.rollingResistance)),w.point);}
 w.omega+=(torque-fx*c.wheelRadius)/c.wheelInertia*dt;w.omega*=Math.exp(-.06*dt);w.omega=clamp(w.omega,-500,500);w.angle=(w.angle+w.omega*dt)%(Math.PI*2);w.longForce=fx;w.sideForce=fy;w.rpm=w.omega*60/(2*Math.PI);s['wheelRPM_'+w.id]=w.rpm;w.wheelRPM=w.rpm;w.wheelSlip=w.slipRatio;w.contactForce=w.load;w.visualSink=w.contact?(w.surface?.sinkAmount||0):0;}
 const highGrip=this.wheels.filter(w=>w.contact&&w.mu>1).length/4;if(highGrip&&(s.rearLocked||s.centerLocked)){moment[1]-=this.omega[1]*highGrip*(s.rearLocked?settings.rearTurnResistance:0);moment[1]-=this.omega[1]*highGrip*(s.centerLocked?settings.centerTurnResistance:0);}
 // Eight small chassis support points permit resting on the side or roof.
 for(const x of [-.70,.70])for(const z of [-1.5,1.5])for(const y of [.48,1.65]){const point=this.point([x,y,z]),penetration=this.terrain.height(point[0],point[2])+.055-point[1];if(penetration>0){const pv=this.velocityAt(point),n=this.terrain.normal(point[0],point[2]),f=clamp(penetration*c.bodyContact.spring-dot(pv,n)*c.bodyContact.damping,0,40000);apply(scale(n,f),point);const tang=sub(pv,scale(n,dot(pv,n)));apply(scale(tang,-Math.min(c.bodyContact.friction*f/(Math.hypot(...tang)||1),c.mass/(4*dt))),point);}}
 const horizontal=Math.hypot(this.v[0],this.v[2]);force[0]-=this.v[0]*horizontal*c.aeroDrag;force[2]-=this.v[2]*horizontal*c.aeroDrag;this.v=add(this.v,scale(force,dt/c.mass));this.p=add(this.p,scale(this.v,dt));const localMoment=inverse(this.q,moment),localOmega=inverse(this.q,this.omega),gyro=cross(localOmega,localOmega.map((v,i)=>v*c.inertia[i]));const angularAcceleration=rotate(this.q,sub(localMoment,gyro).map((v,i)=>v/c.inertia[i]));this.omega=add(this.omega,scale(angularAcceleration,dt));this.omega=scale(this.omega,Math.exp(-.16*dt));const [qx,qy,qz,qw]=this.q,[wx,wy,wz]=this.omega;this.q=[qx+(wx*qw+wy*qz-wz*qy)*dt/2,qy+(-wx*qz+wy*qw+wz*qx)*dt/2,qz+(wx*qy-wy*qx+wz*qw)*dt/2,qw+(-wx*qx-wy*qy-wz*qz)*dt/2];this.q=scale(this.q,1/Math.hypot(...this.q));for(const i of [0,2])if(Math.abs(this.p[i])>c.mapLimit){this.p[i]=Math.sign(this.p[i])*c.mapLimit;this.v[i]=0;}
 s.frontAxleRPM=(this.wheels[0].rpm+this.wheels[1].rpm)/2;s.rearAxleRPM=(this.wheels[2].rpm+this.wheels[3].rpm)/2;s.vehicleSpeed=Math.hypot(this.v[0],this.v[2])*3.6;s.throttle=clamp(s.throttle,0,1);if(!s.wheels)s.wheels=this.wheels.map(w=>({id:w.id}));for(let i=0;i<4;i++){const w=this.wheels[i],out=s.wheels[i];out.surfaceType=w.surfaceType||'DIRT';out.wheelSlip=w.wheelSlip;out.wheelRPM=w.rpm;out.contactForce=w.load;out.mudDepth=w.mudDepth||0;out.waterDepth=w.waterDepth||0;}
 }
 matrix(){const right=rotate(this.q,[1,0,0]),up=rotate(this.q,[0,1,0]),front=rotate(this.q,[0,0,1]),origin=sub(this.p,rotate(this.q,this.c.centerOfMass));return new Float32Array([...right,0,...up,0,...front,0,...origin,1]);}
}
