import {SURFACE_CONFIG,SURFACE_SETTINGS} from './surfaces.js?v=007';
export const ROAD_CONFIG={activeSections:7,behind:2,ahead:4,lengths:[40,54,68],widths:[6.4,7.2,8.0],corridor:48,treeLimit:38,step:2,maxHeadingOffset:.60,maxCurve:.32,seed:731024};
export const SECTION_TYPES=['STRAIGHT','CURVE_LEFT','CURVE_RIGHT','MUD','HILL','FORD'];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),smooth=x=>{x=clamp(x,0,1);return x*x*(3-2*x);};
export class RoadWorld{
 constructor(seed=ROAD_CONFIG.seed){this.reset(seed);}
 random(){this.rng=(Math.imul(this.rng,1664525)+1013904223)>>>0;return this.rng/4294967296;}
 reset(seed=this.seed){this.seed=Number(seed)>>>0;this.rng=this.seed;this.sections=[];this.bins=new Map();this.binsDirty=true;this.nextId=0;this.distance=0;this.offset=[0,0];this.revision=(this.revision||0)+1;this.current=null;for(let i=0;i<ROAD_CONFIG.activeSections;i++)this.append();this.current=this.sections[0];}
 choose(){const warm=['STRAIGHT','STRAIGHT','CURVE_RIGHT','STRAIGHT'];if(this.nextId<4)return warm[this.nextId];const prev=this.sections.at(-1),last=this.sections.slice(-2);if(prev?.type==='FORD'||prev?.type==='MUD'||last.every(s=>['HILL','MUD','FORD'].includes(s.type)))return 'STRAIGHT';const r=this.random();return r<.30?'STRAIGHT':r<.49?'CURVE_LEFT':r<.68?'CURVE_RIGHT':r<.83?'MUD':r<.95?'HILL':'FORD';}
 append(){const previous=this.sections.at(-1),entry=previous?{...previous.exitTransform}:{x:0,y:0,z:40,yaw:Math.PI,width:7.2},type=this.choose(),length=ROAD_CONFIG.lengths[Math.floor(this.random()*3)],exitWidth=ROAD_CONFIG.widths[Math.floor(this.random()*3)],difficulty=Math.floor(this.random()*3),template=Math.floor(this.random()*3);let turn=type==='CURVE_LEFT'?.18+this.random()*.14:type==='CURVE_RIGHT'?-(.18+this.random()*.14):0;turn=clamp(entry.yaw+turn,Math.PI-ROAD_CONFIG.maxHeadingOffset,Math.PI+ROAD_CONFIG.maxHeadingOffset)-entry.yaw;
 // Monotonic Z is a geometric guarantee against road self-intersection.
 let deltaY=type==='HILL'?[1.8,3.2,4.6][difficulty]*(this.random()<.35?-1:1):0;const id=this.nextId++,startDistance=previous?previous.startDistance+previous.length:0,section={id,type,length,width:entry.width,entryTransform:entry,startDistance,difficulty,template,surface:type==='MUD'?'MUD':type==='FORD'?'WATER':'DIRT',obstacles:[],nodes:[],decorations:[]};const count=Math.ceil(length/ROAD_CONFIG.step);let x=entry.x,z=entry.z;
 for(let i=0;i<=count;i++){const u=i/count,yaw=entry.yaw+turn*smooth(u);if(i){const mid=(i-.5)/count,angle=entry.yaw+turn*smooth(mid);x+=Math.sin(angle)*length/count;z+=Math.cos(angle)*length/count;}const envelope=Math.sin(Math.PI*u)**2,y=entry.y+deltaY*smooth(u)+(type==='FORD'?-.16:type==='MUD'?-.035:.10)*envelope;section.nodes.push({x,y,z,yaw,width:entry.width+(exitWidth-entry.width)*smooth(u),u,s:startDistance+u*length});}
 const end=section.nodes.at(-1);section.exitTransform={x:end.x,y:entry.y+deltaY,z:end.z,yaw:end.yaw,width:exitWidth};section.startHeight=entry.y;section.endHeight=section.exitTransform.y;section.entryDirection=entry.yaw;section.exitDirection=end.yaw;
 for(let i=0;i<32;i++){const node=section.nodes[1+Math.floor(this.random()*(count-1))],side=i%2?-1:1,offset=side*(node.width/2+4+this.random()*27),scale=2.8+this.random()*3.4,variant=Math.floor(this.random()*3);section.decorations.push({kind:'tree',x:node.x+Math.cos(node.yaw)*offset,z:node.z-Math.sin(node.yaw)*offset,y:node.y+.025*Math.max(0,Math.abs(offset)-node.width/2),scale,rotation:this.random()*6.28,variant});}
 for(let i=0;i<7;i++){const node=section.nodes[Math.floor(this.random()*count)],side=i%2?-1:1,offset=side*(node.width/2+1+this.random()*4);section.decorations.push({kind:i%3?'bush':'stone',x:node.x+Math.cos(node.yaw)*offset,z:node.z-Math.sin(node.yaw)*offset,y:node.y,scale:.35+this.random()*.55,rotation:this.random()*6.28});}
 this.sections.push(section);this.binsDirty=true;return section;}
 indexSegments(){this.bins.clear();for(const section of this.sections)for(let i=0;i<section.nodes.length-1;i++){const a=section.nodes[i],b=section.nodes[i+1],entry={section,i,a,b};for(let cell=Math.floor((b.z-32)/12);cell<=Math.floor((a.z+32)/12);cell++){if(!this.bins.has(cell))this.bins.set(cell,[]);this.bins.get(cell).push(entry);}}this.binsDirty=false;}
 locate(x,z){if(this.binsDirty)this.indexSegments();let best=null,distance=Infinity;const candidates=this.bins.get(Math.floor(z/12))||[...this.bins.values()].flat();for(const {section,i,a,b} of candidates){const dx=b.x-a.x,dz=b.z-a.z,t=clamp(((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz),0,1),cx=a.x+dx*t,cz=a.z+dz*t,d=(x-cx)**2+(z-cz)**2;if(d<distance){distance=d;const yaw=a.yaw+(b.yaw-a.yaw)*t;best={section,t,index:i,x:cx,z:cz,y:a.y+(b.y-a.y)*t,yaw,width:a.width+(b.width-a.width)*t,u:a.u+(b.u-a.u)*t,s:a.s+(b.s-a.s)*t,lateral:(x-cx)*Math.cos(yaw)-(z-cz)*Math.sin(yaw)};}}return best;}
 update(x,z){const point=this.locate(x,z);this.current=point.section;this.distance=Math.max(this.distance,point.s-18);while(this.sections.at(-1).id<this.current.id+ROAD_CONFIG.ahead)this.append();while(this.sections.length>ROAD_CONFIG.activeSections&&this.sections[0].id<this.current.id-ROAD_CONFIG.behind)this.sections.shift(),this.binsDirty=true;return point;}
 height(x,z){const p=this.locate(x,z),outside=Math.max(0,Math.abs(p.lateral)-p.width/2);return p.y+.025*outside+.12*Math.sin(p.lateral*.2)**2*smooth(outside/5);}
 normal(x,z){const h=.08,a=this.height(x-h,z)-this.height(x+h,z),b=this.height(x,z-h)-this.height(x,z+h),length=Math.hypot(a,2*h,b);return[a/length,2*h/length,b/length];}
 surface(x,z){const p=this.locate(x,z),env=Math.sin(Math.PI*p.u)**2,edge=Math.abs(p.lateral),onRoad=edge<p.width/2;let surfaceType=onRoad?'DIRT':'SOFT_DIRT',mudDepth=0,waterDepth=0;
 if(onRoad&&p.section.type==='MUD'&&env>.035){const template=p.section.template,rut=template===0?1:template===1?(p.lateral<0?1:.12):(Math.abs(Math.abs(p.lateral)-1)<.55?1:.2);mudDepth=(.16+.10*p.section.difficulty)*env*rut;surfaceType='MUD';}
 if(onRoad&&p.section.type==='FORD'&&env>.06){surfaceType='WATER';waterDepth=.16*env;}
 const c={...SURFACE_CONFIG[surfaceType]};if(surfaceType==='MUD'){c.longitudinalGrip*=1-SURFACE_SETTINGS.mudGripLoss*mudDepth;c.lateralGrip*=1-.45*mudDepth;c.rollingResistance+=SURFACE_SETTINGS.mudResistance*mudDepth;c.sinkAmount=Math.min(.10,c.sinkAmount*mudDepth);}if(surfaceType==='WATER')c.rollingResistance+=waterDepth*SURFACE_SETTINGS.waterResistance;return{surfaceType,mudDepth,waterDepth,...c};}
 point(section=this.current,u=.15){const f=clamp(u,0,.95)*(section.nodes.length-1),i=Math.floor(f),a=section.nodes[i],b=section.nodes[i+1],t=f-i;return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t,yaw:a.yaw+(b.yaw-a.yaw)*t};}
 shift(dx,dz){for(const s of this.sections){for(const n of s.nodes){n.x-=dx;n.z-=dz;}for(const tr of [s.entryTransform,s.exitTransform,...s.decorations]){tr.x-=dx;tr.z-=dz;}}this.offset[0]+=dx;this.offset[1]+=dz;this.revision++;this.binsDirty=true;}
}
