import {rotate} from './physics.js?v=011';
export const TREE_CONFIG={gridSize:8,maxFalling:24,fallDuration:3,halfWidth:.87,halfLength:1.90,contactHeight:.30,types:{SMALL:{radius:.12,breakSpeed:4,loss:.16},MEDIUM:{radius:.25,breakSpeed:8,loss:.45},LARGE:{radius:.46,breakSpeed:Infinity,loss:1}}};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export class TreeCollisions{
 constructor(world,feedback){this.world=world;this.feedback=feedback;this.grid=new Map();this.signature='';this.falling=[];this.lastHit={type:'—',impulse:0,time:-10};this.time=0;}
 rebuild(){this.grid.clear();for(const section of this.world.sections)for(const tree of section.decorations)if(tree.kind==='tree'&&!tree.broken){const key=Math.floor(tree.x/TREE_CONFIG.gridSize)+','+Math.floor(tree.z/TREE_CONFIG.gridSize);if(!this.grid.has(key))this.grid.set(key,[]);this.grid.get(key).push({tree,section});}this.signature=this.world.nextId+':'+this.world.revision;}
 tick(dt,body){this.time+=dt;for(const f of this.falling)f.age+=dt;this.falling=this.falling.filter(f=>f.age<TREE_CONFIG.fallDuration&&this.world.sections.some(s=>s===f.section));if(this.signature!==this.world.nextId+':'+this.world.revision)this.rebuild();const gx=Math.floor(body.p[0]/8),gz=Math.floor(body.p[2]/8);for(let x=gx-1;x<=gx+1;x++)for(let z=gz-1;z<=gz+1;z++)for(const item of this.grid.get(x+','+z)||[])this.collide(item,body);}
 collide({tree,section},body){if(tree.broken||body.p[1]<tree.y-.3||body.p[1]>tree.y+tree.scale+1)return;const settings=TREE_CONFIG.types[tree.category||'MEDIUM'],radius=tree.radius||settings.radius,front=rotate(body.q,[0,0,1]),yaw=Math.atan2(front[0],front[2]),c=Math.cos(yaw),s=Math.sin(yaw),dx=tree.x-body.p[0],dz=tree.z-body.p[2],lx=dx*c-dz*s,lz=dx*s+dz*c;
 let cx=clamp(lx,-TREE_CONFIG.halfWidth,TREE_CONFIG.halfWidth),cz=clamp(lz,-TREE_CONFIG.halfLength,TREE_CONFIG.halfLength),nx=lx-cx,nz=lz-cz,d=Math.hypot(nx,nz);if(d>=radius)return;if(d<1e-6){if(TREE_CONFIG.halfWidth-Math.abs(lx)<TREE_CONFIG.halfLength-Math.abs(lz)){nx=Math.sign(lx)||1;nz=0;cx=(Math.sign(lx)||1)*TREE_CONFIG.halfWidth;}else{nz=Math.sign(lz)||1;nx=0;cz=(Math.sign(lz)||1)*TREE_CONFIG.halfLength;}d=-Math.min(TREE_CONFIG.halfWidth-Math.abs(lx),TREE_CONFIG.halfLength-Math.abs(lz));}else{nx/=d;nz/=d;}
 // Normal points from the trunk toward the nearest body face.
 const normal=[-(nx*c+nz*s),0,-(-nx*s+nz*c)],contact=[body.p[0]+cx*c+cz*s,body.p[1],body.p[2]-cx*s+cz*c],rx=contact[0]-body.p[0],rz=contact[2]-body.p[2],vn=(body.v[0]+body.omega[1]*rz)*normal[0]+(body.v[2]-body.omega[1]*rx)*normal[2],closing=Math.max(0,-vn),lever=rz*normal[0]-rx*normal[2],effective=1/body.c.mass+lever*lever/body.c.inertia[1],impulse=closing/effective,shouldBreak=closing>settings.breakSpeed;let breakEvent=null;
 if(shouldBreak){const direction=[-normal[0],-normal[2]],speed=Math.hypot(body.v[0],body.v[2])||1;direction[0]=direction[0]*.55+body.v[0]/speed*.45;direction[1]=direction[1]*.55+body.v[2]/speed*.45;const len=Math.hypot(...direction)||1;direction[0]/=len;direction[1]/=len;tree.broken=true;section.decorationRevision++;if(this.falling.length<TREE_CONFIG.maxFalling)this.falling.push({tree,section,age:0,direction});const j=impulse*settings.loss;body.v[0]+=normal[0]*j/body.c.mass;body.v[2]+=normal[2]*j/body.c.mass;body.omega[1]+=lever*j/body.c.inertia[1];breakEvent={treeType:tree.category,impulse:j,position:[tree.x,tree.y,tree.z]};}
 else{const correction=Math.max(.005,radius-Math.min(d,radius));body.p[0]+=normal[0]*correction;body.p[2]+=normal[2]*correction;if(closing>0){body.v[0]+=normal[0]*impulse/body.c.mass;body.v[2]+=normal[2]*impulse/body.c.mass;body.omega[1]+=lever*impulse/body.c.inertia[1];}}
 if(closing>.5&&this.time-(tree.lastHitTime??-10)>.2){tree.lastHitTime=this.time;this.lastHit={type:tree.category,impulse:shouldBreak?impulse*settings.loss:impulse,time:this.time};this.feedback.emit('treeHit',{treeType:tree.category,impulse:this.lastHit.impulse,position:[tree.x,tree.y,tree.z]});}if(breakEvent)this.feedback.emit('treeBreak',breakEvent);
 }
 clear(){this.falling=[];this.signature='';this.lastHit={type:'—',impulse:0,time:-10};}
}
